### ISSUE TITLE
Constraint on text outline is ambiguous.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#102]
In 7.4 is stated:

#textOutline	permitted	If specified, the border thickness shall be 10% or less than the associated font size.

This needs to be written in terms of the computed style set since the associated font size cannot be determined until the CSS is computed.

**Comment by skynavga** [comment]
As it turns out, my original suggestion for new text is somewhat inadequate in the sense that the computed style value of the associated font size can't be determined until its computed value is used. For example, the computed value of a font size may use percentage or viewport units which cannot be resolved until layout time. In CSS, these are called *used values*.

**Comment by palemieux** [comment]
In TTML1, there are no viewport units, so the relationship between fontSize and textOutline can always be determined at authoring time, right? Regardless, should the text say "computed values" or "used values"?

**Comment by skynavga** [comment]
if font size is not specified in the <span*,p,div,body,region> ancestors, then the region's font size is set to the initial value of '1c' and inherited by all content in the region; since 1c is dependent on the root container extent, then if no extent is specified on the root element, then 1c can't be resolved until rendering time

**Comment by palemieux** [comment]
> since 1c is dependent on the root container extent, then if no extent is specified on the root element, then 1c can't be resolved until rendering time

fontSize="1c" = 1/15 of root container height (assuming ttp:cellResolution is not set to something else), so it can be determined as a percentage of the root container at time of authoring.

**Comment by skynavga** [comment]
ah, right, scratch my latest comment

**Comment by palemieux** [comment]
it still sounds like "used value" should be used instead of "computed value" since textOutline could be specified as "0.1em" and fontSize as "2c", right?

**Comment by skynavga** [comment]
that would be true in TTML1, but 'c' units can't be used with font size in IMSC1, yes?

**Comment by palemieux** [comment]
Right. Bad example. textOutline could be specified as "0.1em" and fontSize as "75%".

**Comment by skynavga** [comment]
right, but 0.1em is the same as 10% on text outline

**Comment by palemieux** [comment]
Ok. What about fontSize="75%" and textOutline="4px".

**Comment by skynavga** [comment]
in that case extent must appear on root, so we can resolve 1c, and thus resolve any percentage font size

**Comment by palemieux** [comment]
Yes.... so "computed" works?

**Comment by skynavga** [comment]
that is my current conclusion
