### ISSUE TITLE
Nested span feature prohibition is redundant in image profile.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#113]
Section 8.4 has both:

#nested-span	prohibited	

and

#content	permitted	The p, span and br elements shall not be present.

The former is thus redundant since no span is permitted.

**Comment by nigelmegitt** [comment]
Not sure exactly what the issue is here - leaving as is causes no problems?

**Comment by skynavga** [comment]
The problem is that it can't be tested, since the prohibition on span masks
attempts to test nested span.

**Comment by nigelmegitt** [comment]
Hmm. What would the test be: count(//span//span) == 0 ? This would always pass for documents with no spans, so that's fine isn't it?

If you construct a document with nested spans but no spans then you're a magician since they're logically exclusive scenarios. If you create a document with a span but no nested span then you'd fail a different test.

**Comment by skynavga** [comment]
On Tue, Dec 8, 2015 at 8:34 AM, nigelmegitt <notifications@github.com>
wrote:

> Hmm. What would the test be: count(//span//span) == 0 ? This would always
> pass for documents with no spans, so that's fine isn't it?
>
> If you construct a document with nested spans but no spans then you're a
> magician since they're logically exclusive scenarios. If you create a
> document with a span but no nested span then you'd fail a different test.
>
The point is that if you have a test for any span fail then a test for
nested span means nothing.

**Comment by nigelmegitt** [comment]
That test for nested span would of course always pass, agreed. What do you want to happen here? Some kind of language in the spec to indicate that it's unnecessary to test for nested spans?

**Comment by skynavga** [comment]
In the comment section for the disposition, please add something like:

"This constraint may be untestable in certain processors due to the
overriding constraint that prohibits the use of any span element."

**Comment by nigelmegitt** [comment]
Works for me

**Comment by palemieux** [comment]
I have added a note to the effect that the prohibition of span elements by the image profile implies the prohibition of the #nested-span feature.

**Comment by nigelmegitt** [comment]
LGTM
