### ISSUE TITLE
Ambiguous disposition of #bidi in image profile.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#115]
The disposition listed in 8.4 for #bidi is ambiguous:

#bidi		See individual disposition of each of the implied features listed at Section D.1.6 of [TTML1]: some implied features are prohibited, others are permitted.

Should enumerate which dependent features are permitted and which are prohibited.

**Comment by nigelmegitt** [comment]
The dependent features are also listed. Why should they be enumerated again in #bidi? Is this just for convenience?

**Comment by skynavga** [comment]
Because "some" and "other" are not specified in the text. Why force the
reader to track down which are which?

**Comment by nigelmegitt** [comment]
I agree it would be an informative convenience to list the dependent features. In general the reader must do a lot of tracking back through TTML, XSL-FO, SMIL and XML specs to truly understand what an IMSC profile requires though.
