### ISSUE TITLE
Ambiguous disposition of #writingMode in image profile.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#117]
The disposition listed in 8.4 for #writingMode is ambiguous:

#writingMode		See individual disposition of each of the implied features listed at Section D.1.109 of [TTML1]: some implied features are prohibited, others are permitted.

Should enumerate which dependent features are permitted and which are prohibited.

**Comment by nigelmegitt** [comment]
The dependent features are also listed. Why should they be enumerated again in #writingMode? Is this just for convenience?

**Comment by skynavga** [comment]
Because "some" and "other" are not specified in the text. Why force the
reader to track down which are which?

**Comment by nigelmegitt** [comment]
Can we collapse all of these discussions in to #115? The repetition isn't really helping!
