### ISSUE TITLE
Why is display align not permitted in image profile?

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#118]
Display align is allowed in text, but not in image profile. Why? It has as much applicability in the latter as the former.

**Comment by nigelmegitt** [comment]
My understanding of this is that since the images must be sized identically to the regions display align would have no effect.

**Comment by skynavga** [comment]
Because "some" and "other" are not specified in the text. Why force the
reader to track down which are which?

**Comment by nigelmegitt** [comment]
References to "some" and "other"?

**Comment by skynavga** [comment]
I had been looking for that text (late) last night but didn't find it, but
I see it now. That raises the issue of why multiple divs are allowed in a
region.

**Comment by nigelmegitt** [comment]
It seems reasonable to permit a region to have multiple child divs that do not temporally overlap.

**Comment by skynavga** [comment]
True, but there is no constraint (at present) on the presence of multiple
divs in a regiion in a single ISD.

**Comment by nigelmegitt** [comment]
That does seem to be a bug.

**Comment by palemieux** [comment]
See Section 8.2 at https://rawgit.com/w3c/imsc/issue-97/spec/ttml-ww-profiles.html 

There is at most at most one presented image per presented region.

**Comment by skynavga** [comment]
But that doesn't prevent two divs from being assigned to a region in the
same ISD, both having a background image. There should be a constraint of
one div per region in a given ISD.

**Comment by palemieux** [comment]
How would two `div` elements, both with a background image and both flowed into the same region in the same ISD, not contradict the restriction that _There is at most at most one presented image per presented region_?

The intent is for a single div with background image per region in a given ISD. I do not claim that the current text is not broken, but would like to understand why.

**Comment by skynavga** [comment]
On Wed, Dec 9, 2015 at 6:33 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> How would two div elements, both with a background image and both flowed
> into the same region in the same ISD, not contradict the restriction that *There
> is at most at most one presented image per presented region*?
>
> The intent is for a single div with background image per region in a given
> ISD. I do not claim that the current text is not broken, but would like to
> understand why.
>
A second div could have no background image, or it could have an image that
overflows the region.

I question the manner in which you expressed the original constraint: in
terms of one presented image.

I would have simply required no more than one div.

**Comment by palemieux** [comment]
Thanks for clarifying

**Comment by palemieux** [comment]
What are the dimensions of a `div` that contains no content?

**Comment by skynavga** [comment]
As you might expect, [0,0], but as I said, one could have two divs, each
with background image, one of which is presented, and which image geometry
matches region geometry, and a second (third etc) with a background image
which overflows the region (and if overflow is hidden) then is not
presented (and thus satisfies your no more than one presented image
constraint).

**Comment by palemieux** [comment]
The pull requests #123 constrains the number of `div` elements to at most one in presented regions.
