### ISSUE TITLE
Interoperability goals not documented

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#126]
A number of important assumptions as well as features present in IMSC are based on interoperability goals that are not documented in the specification or elsewhere. Because a reader may not necessarily know or share these assumptions, both content and implementations may be less interoperable than desired.

This subject should be treated informatively, in introductory material (preferably); otherwise, in an appendix.

The following subjects should be addressed:

* whether and how content that conforms to some SMPTE-TT (ST2052) profile should be treated by an IMSC compliant processor (of either IMSC profile);

* whether and how content that conforms to some EBU-TT profile should be treated by an IMSC compliant processor (of either IMSC profile);

* whether and how content that conforms to some TTML1 or SDP-US profile should be treated by an IMSC compliant processor (of either IMSC profile);

* the converse of the above three subjects

These subjects should be treated from both the perspective of content conformance and of processor conformance.

**Comment by nigelmegitt** [comment]
One specific issue related to this is that SMPTE-TT and SDP-US each mandate that a specific ttp:profile attribute value be included; the presence of this attribute value does not mean that the document is _not_ IMSC text or image profile conformant in every other respect: the treatment of text profile conformant documents that are labelled by ttp:profile as being SMPTE-TT or SDP-US documents needs to be explained in this proposed section (which I guess is the point of the issue); likewise the treatment of image profile documents labelled by ttp:profile as being SMPTE-TT documents.

**Comment by skynavga** [comment]
Regarding SDP-US, it requires the presence of an ttp:profile element (not attribute), with a specific value for the `use` attribute, namely:

<pre>
&lt;ttp:profile use="http://www.w3.org/ns/ttml/profile/sdp-us"/&gt;
</pre>

Since IMSC1 prohibits use of the ttp:profile element, it appears that IMSC is not interoperable with SDP-US. It also appears that the following statement in IMSC1 abstract and scope is not accurate:

"The text profile is a strict superset of [ttml10-sdp-us]."

**Comment by skynavga** [comment]
Regarding SMPTE-TT (ST 2052-1:2013), there is no evidence that the `@ttp:profile` attribute is required; rather, the following text appears to require some form of reference, which might be accomplished with either the `@ttp:profile` attribute or `ttp:profile` element.

"This profile shall be referenced in a conforming SMPTE-TT document by the designator: `http://www.smpte- ra.org/schemas/2052-1/2013/profiles/smpte-tt-full`."

**Comment by palemieux** [comment]
IMSC-T and IMSC-I processors only process documents that conform to IMSC-T and IMSC-I document profiles, respectively.

It is possible to create SMPTE-TT, EBU-TT-D and SDP-US documents that also conforms to IMSC-T profile, and SMPTE-TT documents that conform to IMSC-I profile.

Would it help to include the former statement explicitly?

**Comment by skynavga** [comment]
Insufficient. Needs more depth and discussion of details, with examples.

**Comment by palemieux** [comment]
I encourage you to provide some for consideration by the group.

**Comment by palemieux** [comment]
See proposal at PR #164
