### ISSUE TITLE
Extensibility goals not documented

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#127]
Some treatment should be explicitly given to the subject of (forward and backward) extensibility, including:

* general treatment of unknown vocabulary and unknown values of known attribute vocabulary
* treatment of an IMSC2 document by an IMSC1 processor
* treatment of an IMSC1 document by an IMSC2 processor

**Comment by nigelmegitt** [comment]
My understanding is that the TTML1 extensibility mechanisms apply to IMSC 1 unless excepted (which they are not).

We do need to decide what IMSC 2 will look like in terms of backward/forward compatibility with IMSC 1 so we understand constraints/freedoms to change.

**Comment by palemieux** [comment]
> general treatment of unknown vocabulary and unknown values of known attribute vocabulary

See Section 6.2 of IMSC1, which allows elements and attributes that are neither specifically permitted nor forbidden by a profile.

> treatment of an IMSC2 document by an IMSC1 processor
> treatment of an IMSC1 document by an IMSC2 processor

Both of these important issues need to move to IMSC2, as they cannot be resolved within the scope of IMSC1 alone.

**Comment by skynavga** [comment]
On Tue, Jan 26, 2016 at 5:59 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> general treatment of unknown vocabulary and unknown values of known
> attribute vocabulary
>
> See Section 6.2 of IMSC1, which allows elements and attributes that are
> neither specifically permitted nor forbidden by a profile.
>
> treatment of an IMSC2 document by an IMSC1 processor
> treatment of an IMSC1 document by an IMSC2 processor
>
> Both of these important issues need to move to IMSC2, as they cannot be
> resolved within the scope of IMSC1 alone.
>
Both of these can be discussed by substituting "future version of an IMSC
processor" for "IMSC2 processor".

**Comment by nigelmegitt** [comment]
My extensibility/interoperability goals for IMSC are:
* documents shall not be extended with TTML syntax etc that is prohibited by the profile being signalled
* we should be able to create future profiles that support everything in IMSC 1 text or image profile plus other features as needed
* we should be able to specify processors for such future profiles that can process IMSC 1 documents as per IMSC 1 specification
* it should be possible to include external namespace content without affecting processing as per the IMSC profile that applies, including global (no) namespace attributes and elements
* transformation processors should ideally carry through any external namespace content, depending of course on what kind of transformation is being done.
* it should be possible to include IMSC documents within other XML document types

I don't have a goal that other elements be inserted within the TTML hierarchy. For example I would not need this transformation to be supported:

```xml
<div>
  <p>
    <span>Some text here</span>
  </p>
</div>
```

becomes:

```xml
<div>
  <goofyWrapperElement>
    <p>
      <span>Some text here</span>
    </p>
  </goofyWrapperElement>
</div>
```

I may have other goals I haven't thought of yet...
