### ISSUE TITLE
Testsuite tests dece/*/*.ttml are mostly non-conformant.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#132]
Most test files in the dece/*/*.ttml directories are non-conformant because they make use of frame values in time expressions but fail to specify ttp:frameRate. In some cases, they also redundantly specify ttp:tickRate but do not use the tick metric.

**Comment by palemieux** [comment]
It looks like ttp:frameRate should be set to 30 and ttp:tickRate removed for completeness.
