### ISSUE TITLE
Testsuite tests using text profile do not specify non-normal line height.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#133]
Some tests that use IMSC Text Profile fail to follow recommendation on specifying non-normal line height as indicated by:

> `#lineHeight`
> An explicit &lt;length&gt; SHOULD be specified as there is no uniform implementation of
> the "normal" value at the time of this writing.

These tests include:

aspectRatio1
aspectRatio2
aspectRatio5
forcedDisplay1
frameSync1
linePadding1
multiRowAlign1
progressivelyDecodable1

and most dece/*/*.ttml tests that use text profile.

In the case of some dece tests, a non-normal (non-default) line height is specified to apply for some text but not for all text.

**Comment by palemieux** [comment]
The explicit length is only a recommendation ("SHOULD"), so I do not believe a change is necessary here. More specifically, I would rather not risk changing the test suite at this point of the process unless absolutely required.

**Comment by skynavga** [comment]
SHOULD means SHOULD. We should follow the recommendation unless you can
show a technical reason why this is a risk.

**Comment by palemieux** [comment]
See proposed disposition to #130.

**Comment by skynavga** [comment]
I restored the bug label because I believe it is a bug to have a test produce a warning unless it is the express intent of the test to verify the production of the warning.

**Comment by nigelmegitt** [comment]
Notes from today's TTWG meeting: the view is to update all tests so that they do not generate warnings from processors that check for conformance with specification recommendations, unless the specific goal of the test is to check that such warnings are issued when they apply.
