### ISSUE TITLE
The term 'boundary' is not defined.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#146]
The term 'boundary' is used in 6.7.1 and 6.8.2 without a definition. Presumably it means the zero width lines located between pixel boundaries in the coordinate space grid. However, this interpretation would not apply when performing intersection tests.

Perhaps the term 'border', as in "optional region border" is intended instead? If so, then it isn't necessary to say "including the border", since a region's extent effectively corresponds to the _border area_ [1] or _border rectangle_ [2] already.

[1] https://www.w3.org/TR/CSS21/box.html
[2] https://www.w3.org/TR/xsl/#area-intro

**Comment by palemieux** [comment]
"edge", i.e. as in the edge of a polygon in classic geometry, could be a less ambiguous term than "boundary".

**Comment by skynavga** [comment]
not really, because you don't say what you mean by boundary or edge; e.g., does it have a width? if not, then it isn't worth mentioning; if it does, then it is mislabeled, since this would refer to a part of the region's border rectangle already; best to just remove all instances of "including the boundary".

**Comment by palemieux** [comment]
Per 20160211 telecon: "including the boundary" is removed throughout the document (see minutes)
