### ISSUE TITLE
Change profile signalling in files with ebu-tt-d extensions

### ISSUE THREAD

**Issue by tairt** [w3c/imsc#148]
The test suites samples for line padding and multirow align have been drafted to be compatible with EBU-TT-D. They were not any more due to the addition of the ttp:profile attribute.

Therefore the indication of the profiles should be done as proposed in the spec using the ebuttm:conformsToStandard element.

**Comment by tairt** [comment]
3f5eac2ce04fbc558ffabbcd4705faa6540bd2ed has a proposed fix. The pull request https://github.com/w3c/imsc/pull/149 has been made to merge this fix.

**Comment by palemieux** [comment]
This is intended to fix a bug introduced when PR #140 was merged.
