### ISSUE TITLE
HRM should be a processor compliance test and allow different levels of complexity for different use cases

### ISSUE THREAD

**Issue by plehegar** [w3c/imsc#15]
The Hypothetical Render Model is defined as a content profile constraint, which appears to set a maximum complexity on all documents. It would be better to make it a minimal processor profile constraint, i.e. so that it can be used to construct maximally complex test documents that compliant processors must be able to process successfully, while permitting processors to process even more complex documents.

This would open up the possibility for future increases in complexity by allowing the threshold values for sub-profiles of IMSC to be changed to 'greater complexity', in the knowledge that pre-existing IMSC compliant documents will be continue to be processable. 

Very closely related to this, the HRM (chapter 7) [1] in various places sets threshold parameter values using the wording "Unless specified otherwise, the following table shall specify..." but there is no mechanism for specifying otherwise; chapter 4.7 simply states that all sequences "of intermediate synchronic documents SHALL be reproducible..." without providing any reference to an external location where the parameters in the HRM can be set to other values. 

One possible solution to this is to introduce a 'complexity level' table and list the current parameter values as, for example 'complexity level 1' and change the wording in chapter 4.7 to state that for use cases that need to specify complexity they must either specify an equivalent table with alternative parameter values or use the default 'level 1' values. It should be permitted for processors not to be subject to the HRM values at all, and there should be scope in future versions of IMSC to add more levels, if there is a strong argument for doing so.

[1] http://www.w3.org/TR/ttml-imsc1/#hypothetical-render-model

(raised by Nigel Megitt on 2014-05-23)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/319

**Comment by palemieux** [comment]
Propose to move to the backlog given the lack of practical and specific issues encountered as of today.
