### ISSUE TITLE
Need to rephrase tts:fontFamily recommendation.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#150]
The recommendation in Section 7.4 regarding #fontFamily-generic is not well formed since it effectively permits 'default'. It should be rewritten to read as follows:

The computed value of tts:fontFamily should be "default", "monospaceSerif", or "proportionalSansSerif", where the value "default" shall be treated as equivalent to "monospaceSerif".

**Comment by palemieux** [comment]
The objective is to encourage authors to explicitly set tts:fontFamily to either "monospaceSerif" or "proportionalSansSerif", and to discourage the value of "default", whether set explicitly using the attribute or implicitly through the initial value.

The proposed text above seems to encourage tts:fontFamily to be set to "default".

**Comment by skynavga** [comment]
It doesn't encourage it; rather it allows it. If you don't add "default" to
the list, then a validator would have to emit a warning if "default" is the
computed value. This would be yet one more case where an author needs to do
something special to avoid validation issues, e.g., as is already the case
with tts:linePadding.

Since the current text defines "default" to mean "monospaceSerif", then
there is no problem with leaving default as a viable value.

**Comment by palemieux** [comment]
On Feb 3, 2016 16:06, "Glenn Adams" <notifications@github.com> wrote:
>
> It doesn't encourage it; rather it allows it. If you don't add "default"
to
> the list, then a validator would have to emit a warning if "default" is
the
> computed value.

That is the idea: the author should explicitly specify a value since
default is perhaps not the right value.

>This would be yet one more case where an author needs to do
> something special to avoid validation issues, e.g., as is already the case
> with tts:linePadding.
>
> Since the current text defines "default" to mean "monospaceSerif", then
> there is no problem with leaving default as a viable value.
>
> On Wed, Feb 3, 2016 at 4:33 PM, Pierre-Anthony Lemieux <
> notifications@github.com> wrote:
>
> > The objective is to encourage authors to explicitly set tts:fontFamily
to
> > either "monospaceSerif" or "proportionalSansSerif", and to discourage
the

**Comment by nigelmegitt** [comment]
The email handler garbled Pierre's message, and for reasons I can't fathom a manual edit of his reply to tidy it isn't working either (at least in the Preview), so here's my tidied version of https://github.com/w3c/imsc/issues/150#issuecomment-179546373

> > It doesn't encourage it; rather it allows it. If you don't add "default" to the list, then a validator would have to emit a warning if "default" is the computed value.

> That is the idea: the author should explicitly specify a value since
default is perhaps not the right value.

**Comment by skynavga** [comment]
Ok, then let's use the following:

>The computed value of tts:fontFamily SHOULD be "monospaceSerif" or "proportionalSansSerif", in which case the used value is the computed value. For any other computed value, the used value SHALL be "monospaceSerif".

**Comment by palemieux** [comment]
The intent is to encourage the author to set tts:fontFamily to "monospaceSerif" or "proportionalSansSerif", and specifies what happens when the computed value of tts:fontFamily is "default". It does not however prevent the author to set fontFamily to something other than "monospaceSerif" or "proportionalSansSerif" -- a feature which is used in IMF.

Doesn't the proposal at https://github.com/w3c/imsc/issues/150#issuecomment-182210277 essentially forces the author to use either "monospaceSerif" or "proportionalSansSerif"?

**Comment by skynavga** [comment]
It sounds like a very weak recommendation, so why make a recommendation at all? If the only intent here is to have a common treatment of 'default', then just deal with this latter point, such as in:

>If the computed value of tts:fontFamily is 'default', then the used value of tts:fontFamily SHALL be 'monospaceSerif'.

And leave it at that.

**Comment by palemieux** [comment]
> so why make a recommendation at all?

Reference fonts are defined for "monospaceSerif" and "proportionalSansSerif", so authors should use one of these two font families unless they know what they are doing.

"should" seemed therefore appropriate, but perhaps there is better prose.

**Comment by skynavga** [comment]
I would express it as follows:

>Content authors that wish to enhance reproducibility of line fitting MAY give preference to using the 'monospaceSerif' or 'proportionalSansSerif' generic font families, for which reference font metrics are defined herein.

and then, independently,

>If the computed value of tts:fontFamily is 'default', then the used value of tts:fontFamily SHALL be 'monospaceSerif'.

**Comment by skynavga** [comment]
I use MAY rather than SHOULD above, since the intent here seems to be a weak recommendation, more like a suggestion, and one that should not elicit a warning (by default) in a validator. On the other hand, a validator may provide an optionally enabled warning to detect for content that doesn't follow this suggestion.

**Comment by palemieux** [comment]
> Content authors that wish to enhance reproducibility of line fitting MAY give preference to using the 'monospaceSerif' or 'proportionalSansSerif' generic font families, for which reference font metrics are defined herein.

In absence of specific instructions on the choice of font families, and in order to enhance reproducibility of line fitting, authors are encouraged to use the 'monospaceSerif' or 'proportionalSansSerif' generic font families, for which reference font metrics are defined herein (see Section XXXX).

**Comment by skynavga** [comment]
On Wed, Feb 10, 2016 at 4:57 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> Content authors that wish to enhance reproducibility of line fitting MAY
> give preference to using the 'monospaceSerif' or 'proportionalSansSerif'
> generic font families, for which reference font metrics are defined herein.
>
> In absence of specific instructions on the choice of font families, and in
> order to enhance reproducibility of line fitting, authors are encouraged to
> use the 'monospaceSerif' or 'proportionalSansSerif' generic font families,
> for which reference font metrics are defined herein (see Section XXXX).
>
LGTM. And don't forget the normative (SHALL) language about the treatment
of 'default'.
