### ISSUE TITLE
No defined mechanism for embedding image data.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#159]
Even though SMPTE ST2052 supports embedded images via the smpte:image element, IMSC excludes use of that element. Consequently there is no means to embed an image that is defined. It could be the case that one may use the 'data' URL schema, e.g., smpte:backgroundImage="data:..."; however, IMSC does not at present define which URL schemas should be supported.

**Comment by palemieux** [comment]
Duplicate of #82
