### ISSUE TITLE
Justification for forced display false affecting flow and layout?

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#163]
What is the use case for forced display false affecting layout but not being visible? This is certainly counter to common sense (IMO). If there is a convincing counter example, then perhaps an example should be added to demonstrate. Otherwise, I suggest we have forced display affect tts:display rather than visibility.

**Comment by nigelmegitt** [comment]
These semantics were discussed at length in August 2014, in the context of [Issue-331](https://www.w3.org/AudioVideo/TT/tracker/issues/331) and we agreed that forced display should affect layout.

IIRC the reason is that it would be weird if switching the visibility of non-forced content were to move the positions of forced content.

**Comment by palemieux** [comment]
See #20

**Comment by skynavga** [comment]
First, the forced display mode isn't going to change during a presentation.
Or if it does, it will be at explicit user control, so they shouldn't be
surprised by a changed display.

Second, the only time where positions would vary is if there are multiple
paragraphs, each with different values of forced display, or multiple
spans, each with different values of forced display. In such cases, forcing
layout will end up producing empty spaces in the displayed content (those
spaces being consumed by layout but where the content is invisible).

IMO, it will look worse to have empty spaces in a div or in a p, than to
leave space without content, merely to avoid position changes when
transitioning force display mode.

**Comment by nigelmegitt** [comment]
Nevertheless, that's the semantic we agreed. The empty spaces can be managed I think, and I can certainly see a use case for two simultaneously active `p` elements with different forced display modes. For example:

```xml
<p itts:forced="false" ttm:role="sound">Door slams</p>
<p itts:forced="true" ttm:role="dialog">What was that noise?</p>
```

where "Door slams" is only shown to hard of hearing viewers who have elected to view non-forced subtitles, but "What was that noise?" is a translation visible to all viewers.

If you consider that this could be in a region with `tts:displayAlign="before"` then it would be reasonable for the author to expect the second `p` always to appear in the same place.

**Comment by skynavga** [comment]
On Tue, Feb 9, 2016 at 9:26 AM, Nigel Megitt <notifications@github.com>
wrote:

> Nevertheless, that's the semantic we agreed.
>
Be that as it may, I'm questioning that conclusion. If the group still
thinks it is the correct answer, then I won't press this point, but IMO it
is the wrong conclusion.

> The empty spaces can be managed I think, and I can certainly see a use
> case for two simultaneously active p elements with different forced
> display modes. For example:
>
> <p itts:forced="false" ttm:role="sound">Door slams</p>
> <p itts:forced="true" ttm:role="dialog">What was that noise?</p>
>
> where "Door slams" is only shown to hard of hearing viewers who have
> elected to view non-forced subtitles, but "What was that noise?" is a
> translation visible to all viewers.
>
> If you consider that this could be in a region with
> tts:displayAlign="before" then it would be reasonable for the author to
> expect the second p always to appear in the same place.
>
It would also be reasonable for the author to understand that forced
display mode can cause changes in position, and if they are concerned about
them, they should take care to avoid them, e.g., by  using multiple regions.

**Comment by nigelmegitt** [comment]
> Be that as it may, I'm questioning that conclusion.

Do you have new technical information on which basis we should reopen the decision?

> It would also be reasonable for the author to understand that forced
display mode can cause changes in position, and if they are concerned about
them, they should take care to avoid them, e.g., by  using multiple regions.

That's a reasonable alternate viewpoint, though made harder in practice by the IMSC constraint of a maximum of 4 simultaneously active regions. There's been a strong push back against increasing that number in previous discussions. I would not be happy to make any change that effectively requires authors to use more regions without also increasing that threshold, since we have no data points on the real world impact.

**Comment by skynavga** [comment]
On Tue, Feb 9, 2016 at 10:10 AM, Nigel Megitt <notifications@github.com>
wrote:

> Be that as it may, I'm questioning that conclusion.
>
> Do you have new technical information on which basis we should reopen the
> decision?
>
If the semantics of forced display are tied to tts:display instead of
tts:visibility, then (1) you don't get empty spaces in your layout (which
I'm not convinced is even acceptable to authors/users), and (2) you don't
have to use resources to layout/format content that won't be displayed, and
which otherwise has a performance impact, e.g., has to be counted by the
HRM model.

> It would also be reasonable for the author to understand that forced
> display mode can cause changes in position, and if they are concerned about
> them, they should take care to avoid them, e.g., by using multiple regions.
>
> That's a reasonable alternate viewpoint, though made harder in practice by
> the IMSC constraint of a maximum of 4 simultaneously active regions.
> There's been a strong push back against increasing that number in previous
> discussions.
>
I'm not suggesting increasing that number. Further, the author may simply
accept a change in position in the case that sufficient regions aren't
available.


> I would not be happy to make any change that effectively requires authors
> to use more regions without also increasing that threshold, since we have
> no data points on the real world impact.
>
That's part of the problem here. The decision about  whether to use display
or visibility seems to be arbitrary and lacking real world use cases or
data.

**Comment by nigelmegitt** [comment]
>> Do you have new technical information on which basis we should reopen the decision?

>If the semantics of forced display are tied to tts:display instead of
tts:visibility, then (1) you don't get empty spaces in your layout (which
I'm not convinced is even acceptable to authors/users), and (2) you don't
have to use resources to layout/format content that won't be displayed, and
which otherwise has a performance impact, e.g., has to be counted by the
HRM model.

That's true but not new. On the "acceptable to authors" point, it's hard for us to predict what is the lesser evil - empty spaces (which can be arranged to be transparent and therefore invisible) or content that moves around based on the displayForcedOnlyMode. Given that processors must be performant enough to present the content regardless of displayForcedOnlyMode the performance impact can be discounted.

> That's part of the problem here. The decision about  whether to use display
or visibility seems to be arbitrary and lacking real world use cases or
data.

That's counter to what @palemieux has told us in the past, i.e. that there are multiple real world use cases using the current semantic, based on CFF-TT.

**Comment by skynavga** [comment]
On Wed, Feb 10, 2016 at 3:39 AM, Nigel Megitt <notifications@github.com>
wrote:

> Do you have new technical information on which basis we should reopen the
> decision?
>
> If the semantics of forced display are tied to tts:display instead of
> tts:visibility, then (1) you don't get empty spaces in your layout (which
> I'm not convinced is even acceptable to authors/users), and (2) you don't
> have to use resources to layout/format content that won't be displayed, and
> which otherwise has a performance impact, e.g., has to be counted by the
> HRM model.
>
> That's true but not new. On the "acceptable to authors" point, it's hard
> for us to predict what is the lesser evil - empty spaces (which can be
> arranged to be transparent and therefore invisible) or content that moves
> around based on the displayForcedOnlyMode.
>
Space is not invisible just because nothing is painted. It affects the
placement of surrounding content.

> Given that processors must be performant enough to present the content
> regardless of displayForcedOnlyMode the performance impact can be
> discounted.
>
> That's part of the problem here. The decision about whether to use display
> or visibility seems to be arbitrary and lacking real world use cases or
> data.
>
> That's counter to what @palemieux <https://github.com/palemieux> has told
> us in the past, i.e. that there are multiple real world use cases using the
> current semantic, based on CFF-TT.
>
I would like to see these use cases, i.e., screen shots or simulations
thereof.

**Comment by palemieux** [comment]
See Section 6.2.3.1.6 at http://uvcentral.com/sites/default/files/files/PublicSpecs/CFFMediaFormat-2_2.pdf

**Comment by skynavga** [comment]
ok, so the current language in IMSC is there for compatibility with CFF
only, which itself does not justify that behavior with any real world
examples;

i think the defined behavior is broken (absent real world examples), but I
won't object to leaving this as as; though, i would like to see a note
indicating that the defined behavior in IMSC is to obtain CFF compatibility;

**Comment by skynavga** [comment]
while we are on this point, could you add some text that indicates that
displayForced true on some element applies to all descendent elements in
the ISD tree, i.e., forced true on region means forced true on all content
targeted to region, forced true on body means forced true on all active p,
span, etc in body, etc;

it is not clear from the current text that the above semantics apply; if
they do not apply, then every leaf content element would be forced to
declare forced to true regardless of an ancestor declaring forced true

**Comment by palemieux** [comment]
> while we are on this point, could you add some text that indicates that displayForced true on some element applies to all descendent elements in the ISD tree

Ok. How does this interact with "inherited: yes"?

**Comment by palemieux** [comment]
> i would like to see a note indicating that the defined behavior in IMSC is to obtain CFF compatibility;

Ok. Sounds good.

**Comment by skynavga** [comment]
On Wed, Feb 10, 2016 at 6:51 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> while we are on this point, could you add some text that indicates that
> displayForced true on some element applies to all descendent elements in
> the ISD tree
>
> Ok. How does this interact with "inherited: yes"?
>
ok, that is sufficient...
