### ISSUE TITLE
Fix @lineHeight in multiRowAlign and linePadding tests

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#167]
To maintain EBU-TT-D compatibility and per https://github.com/w3c/imsc/pull/166#issuecomment-182445088, #styling-inline is not permitted in EBU-TT-D, and `@lineHeight` specification should be move from `<body>` to "baseStyle" `<style>` in the multiRowAlign and linePadding tests.

**Comment by nigelmegitt** [comment]
Note that the change to add `tts:lineHeight` to `<body>` was introduced in 4fcb141 on 2016-01-29.
