### ISSUE TITLE
Errata document has wrong text encoding for IRT full name

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#183]
The ü character is incorrectly encoded in the acknowledgment of IRT.

**Comment by nigelmegitt** [comment]
Wait, I may have filed this too soon. PR #182 appeared to have this problem but the version being served at http://www.w3.org/2016/04/ttml-imsc1-errata.html does not.

**Comment by nigelmegitt** [comment]
I'm totally confused by this - https://rawgit.com/w3c/imsc/master/spec/ttml-imsc1-errata.html shows the wrong text but http://www.w3.org/2016/04/ttml-imsc1-errata.html which is supposed to be identical shows the correct text. The sources definitely differ.

@tmichel07 did you make a local fix to the published version to rectify this?

**Comment by tmichel07** [comment]
I have copied  the document from http://www.w3.org/2016/04/ttml-imsc1-errata.html into github.
It displays correctly on the W3C server but still show encoding issue on github at
https://rawgit.com/w3c/imsc/master/spec/ttml-imsc1-errata.html

**Comment by nigelmegitt** [comment]
It's still broken, that's why. Copy/paste editor problem?

**Comment by tmichel07** [comment]
Yes indeed it was a copy/paste editor problem. My editor introduces those issues when coping paste from the document on the W3C server. I had to edit manually ;-(

**Comment by nigelmegitt** [comment]
I suggest configuring your editor to work in UTF-8 and disable any conversions. If your editor doesn't support that, change editor - seriously that is a big problem. I've seen similar problems with line endings where editors do it 'wrong' and every commit looks like the whole file has changed.

**Comment by tmichel07** [comment]
Nigel,

I am using Ultra Edit software.

setting to UTF-8 may work in some cases but there are also all thoses 
files that I need to edit in other European encoding ...

I had used the conversions to UTF-8 but that didn't resolved the problem.

What text editor do you suggest ?

The encoding issue on github is now resolved.
https://rawgit.com/w3c/imsc/master/spec/ttml-imsc1-errata.html

Thierry

**Comment by nigelmegitt** [comment]
Let's move this discussion off the issue - I'll continue by direct email.

**Comment by palemieux** [comment]
@nigelmegitt Can you confirm this is fixed in the currently published errata?

**Comment by nigelmegitt** [comment]
Looks right to me.

**Comment by tmichel07** [comment]
https://www.w3.org/2016/04/ttml-imsc1-errata.html
loks good to me.
thierry

**Comment by palemieux** [comment]
@tmichel07 Can you provide the source of this latest version of the errata so that it can be checked-in the imsc repo?
