### ISSUE TITLE
Potential conflict with respect to pixel aspect ratio.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#184]
IMSC1 permits the simultaneous specification of both ittp:aspectRatio (as an expression of DAR) and tts:extent (as an expression of SAR). If the ratios of these two parameters are different, then the effective pixel aspect ratio (PAR) is not 1:1. However, IMSC1 prohibits the presence of ttp:pixelAspectRatio, and, further, TTML1 requires that in the absence of an ttp:pixelAspectRatio attribute, PAR is 1:1. As a consequence, IMSC1 allows a PAR not equal to 1:1 while making use of TTML1s default PAR of 1:1. Since both cannot be true at once, we have a semantic conflict in the IMSC1 specification.

For example, see EXAMPLE 2 at [1], where we have:

ittp:aspectRatio="4 3" and tts:extent="400px 300px"

Now in this case, both ratios are the same, so PAR is indeed 1:1.

However, nothing prevents the author from specifying tts:extent="300px 400px", in which case we have PAR (= DAR/SAR = 4/3 ÷ 3/4) of 16:9 (1.777..). But since we can't specify ttp:pixelAspectRatio='16 9', we have a defaulted PAR (from TTML1) of 1:1.

[1] https://www.w3.org/TR/ttml-imsc1/#ttp-aspectRatio

**Comment by skynavga** [comment]
I propose a resolution as follows:

TTML2 needs to deal with the general case of over constraint since it will permit all three of ttp:displayAspectRatio (DAR), tts:extent (SAR), and ttp:pixelAspectRatio (PAR) to be specified. Therefore, a constrain relaxation algorithm is required for TTML2 in any case. I propose this algorithm be equivalent to the following:

> If DAR, SAR, and PAR are all specified (or defaulted), and if DAR/SAR is not equal to PAR, then the effective PAR shall be equal to DAR/SAR.

This same approach can be used to resolve this issue.

**Comment by nigelmegitt** [comment]
Sounds reasonable to me.
