### ISSUE TITLE
Create a gh-pages branch for serving the Editor's Drafts

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#187]
At the moment the Editor's Draft link is via rawgit.com which is a 3rd party; since GitHub offers gh-pages to serve HTML we should use that instead; that involves creating a gh-pages branch, as we have done e.g. for https://github.com/w3c/ttml2 and is common practice across other document repos.

**Comment by palemieux** [comment]
`gh-pages` is intended to host websites, not conduct development. See https://help.github.com/articles/what-is-github-pages/ .

**Comment by nigelmegitt** [comment]
Right @palemieux , and our editor's drafts are web pages. I do not think this constitutes "conducting development".

**Comment by palemieux** [comment]
The current system is functionally equivalent without creating additional branches and/or using branches that are meant for other purposes.

**Comment by nigelmegitt** [comment]
Actually it is functionally different, since it relies on a 3rd party service (rawgit) to provide the Editor's draft in a consumable form, and that 3rd party has no direct relationship either with w3c or with github. We do not need to continue with multiple branches, we can make the gh-pages a copy of the current master branch, protect it, then de-protect and remove the master branch.

I'm puzzled: why the resistance here?

**Comment by tmichel07** [comment]
I also think we should move to gh-pages and remove the master branch.
This is general practice in W3C.

**Comment by palemieux** [comment]
Changed (settings)[https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/] allowing github.io to publish from _master_

http://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html
