### ISSUE TITLE
Example 10 - fontHeight problem

### ISSUE THREAD

**Issue by mikedo** [w3c/imsc#189]
In general the resulting fontHeight seriously exceeds the defined regions. The defined regions are too small or the fontHeght is too large.

**Comment by nigelmegitt** [comment]
I can't replicate your issue @mikedo : in Example 10 there is no specified `cellResolution` or `fontSize` so the font size is 1/15 of the root container region (i.e. one standard cell tall), or 6.67%. The region extent height is 10% so a single line of text will fit. The text "Lorem ipsum dolor sit amet." does not look unusually long and I would normally expect it to fit within the extent width of 80% (this is of course font dependent). 

I have looked at all the other examples too and they seem okay.

Can you provide more detail about what is wrong?

**Comment by palemieux** [comment]
It looks like text overflows in Example 10 when rendering it with imscJS.

![0](https://cloud.githubusercontent.com/assets/4871350/21355950/cee1c88a-c684-11e6-9f86-13fddf5923fc.png)

**Comment by nigelmegitt** [comment]
To respond to my own point:

> The text "Lorem ipsum dolor sit amet." does not look unusually long and I would normally expect it to fit within the extent width of 80% (this is of course font dependent).

The imscJS rendering whose output image is copied above does look correct, so I conclude that the only problem with this example is that there's too much text to fit in a single line. This is easily remedied!

**Comment by palemieux** [comment]
I plan to reduce the amount of text.
