### ISSUE TITLE
Control background between adjacent lines

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#195]
Per https://lists.w3.org/Archives/Member/member-tt/2017Jan/0001.html

_We would welcome a feature that allows authorial control of
background areas behind spans such that gaps between background areas on adjacent lines
can be eliminated. We believe there are cases where this improves readability._

See also:
* https://github.com/w3c/ttml2/issues/150
* https://github.com/w3c/ttml2/issues/101
* https://lists.w3.org/Archives/Member/member-tt/2017Jan/0004.html

**Comment by nigelmegitt** [comment]
[Meeting 2017-01-12] Agreed to add:

```
itts:fillLineGap :
   true | false
Inheritable: true
Applies to: p
Animatable: discrete
```

If `itts:fillLineGap="true"` then the background of each inline area generated by descendant spans of the p element is extended to the edges of the containing line area in the block progression dimension.
