### ISSUE TITLE
recommendation for "end" but not "dur"

### ISSUE THREAD

**Issue by mikedo** [w3c/imsc#198]
The following recommendation seems odd:

"For any content element that contains br elements or text nodes or a smpte:backgroundImage attribute, the begin and end attributes SHOULD be specified on the content element or at least one of its ancestors."

On the surface this seems to suggest that content should not have an indefinite end time. However, a side affect of the above is that it discourages the use of dur since validators might be inclined to generate warnings if dur is used instead of end even though the computed end time is unambiguous either way.

Since both end and dur are permitted, I'm not sure what this provision brings to the specification. I believe we should consider deleting it.  Alternatively, consider adding dur.

**Comment by nigelmegitt** [comment]
[Meeting 2017-01-12] Propose to change the recommendation to permit either dur or end but not both.
