### ISSUE TITLE
Behaviour if `ittp:activeArea` is non conformant is unclear

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#211]
The text:

> The Active Area SHALL NOT extend outside the root container in any dimension.

in [6.7.5 ittp:activeArea](https://www.w3.org/TR/ttml-imsc1.0.1/#ittp-activeArea) does not indicate how the value should be treated if it _does_ extend outside the root container region. For example should it initially be clipped by the root container region, or moved so that the dimensions remain the same, if possible, and then if still needed, then clipped?

**Comment by mikedo** [comment]
In spec writing it is a very deep rathole to attempt to document decoder behavior for the thousand ways the input can be non-conformant. We should not go there.  Although strictly, the document can simply be rejected, a good decoder will try to do "something reasonable" which may vary from application to application and whether the decoder is a presentation engine or a transformation processor.

**Comment by nigelmegitt** [comment]
@mikedo you've misunderstood the issue as I've written it. I deliberately avoided defining decoder behaviour, I requested a treatment of the value should it be syntactically valid but arithmetically out of specified range.

Assuming that a legal value is desirable, there are not thousands of ways to create one given a syntactically valid set of input parameters; the specified value can be out of range on the right or the bottom (negative values are prohibited). In that case it is reasonable to indicate a rule such as that the right edge is equal to the lesser of the sum of (x+width) and 100%, and the bottom edge is equal to the lesser of the sum of (y+height) and 100%. This is by the way coincident with what is in the TTML2 equivalent, so it should not be contentious.

**Comment by palemieux** [comment]
@nigelmegitt _the Active Area SHALL NOT extend outside the root container in any dimension_ is intended as document constraint, not a runtime/decoder constraint -- similarly to the requirement that _All regions shall not extend beyond the root container_ in Section 6.8.2. Would clarifying this address your concern?

**Comment by palemieux** [comment]
@nigelmegitt How is that different then the requirement that _all regions shall not extend beyond the root container_ in Section 6.8.2?

**Comment by nigelmegitt** [comment]
@palemieux actually that is another way to do exactly what I'm asking for here:

> All regions shall not extend beyond the root container, i.e. the intersection of the sets of coordinates belonging to a region and the sets of coordinates belonging to the root container is the set of coordinates belonging to the region.

You could reuse similar language if that helps. What this text says to me is that even if the region as specified extends beyond the root container region only that part of it which intersects with the root container region is used when defining the region.

**Comment by palemieux** [comment]
> What this text says to me is that even if the region as specified extends beyond the root container region only that part of it which
> intersects with the root container region is used when defining the region.

The text did not intend to specify a behavior, but instead restate the constraint _shall not extend beyond the root container_ in a different manner.

**Comment by palemieux** [comment]
To be sure, IMSC1 explicitly states that behavior in the case of error conditions is unspecified, as noted in Section 4. I do not see a reason to do differently here.

**Comment by mikedo** [comment]
@nigelmegitt - Defining what a decoder does if the document says X and instructing the decoder to change it to Y before processing is 100% decoder behavior.  Yes, there are thousands of ways IMSC1 documents can be non-conformant (I didn't say this one attribute). Where do we stop?  I am firmly opposed to writing decoder behavior to account for non-conformant documents.

**Comment by nigelmegitt** [comment]
@mikedo since we were willing to accept the text for the constraint on region and this is effectively the same requirement it seems reasonable to me to apply the same approach to activeArea and be done. It is not usually the place of IMSC to define processor fallbacks etc simply because IMSC does not define the syntax or semantics of most of the features it includes. This case is different because IMSC is defining the feature.

@palemieux 
> The text did not intend to specify a behavior, but instead restate the constraint shall not extend beyond the root container in a different manner.

Regardless of the intent, it does actually specify that set of coordinates belonging to a region is the intersection between the specified area and the root container region. I'm struggling to read it any other way, and it clearly is not a syntactic or arithmetic constraint on the specified values for the origin and extent of the region.

I would object to changing this wording now, but I would accept using an appropriately edited variant of it for activeArea.

**Comment by palemieux** [comment]
> I would object to changing this wording now, but I would accept using an appropriately edited variant of it for activeArea.

I would object to specifying a behavior for activeArea, even though the "i.e." following the region constraint can unfortunately be misconstrued as stating something different than the constraint itself.

**Comment by nigelmegitt** [comment]
@palemieux in that case you are introducing an inconsistency into the specification for no apparent benefit.

**Comment by palemieux** [comment]
@nigelmegitt What is the inconsistency?

**Comment by nigelmegitt** [comment]
@palemieux The inconsistency is as follows: in both cases the intent and requirement is to constrain the rectangle so that it does not go outside the root container region; we specify this in two different ways that can be read as meaning different things.

**Comment by palemieux** [comment]
> we specify this in two different ways that can be read as meaning different things.

In both cases, the document is invalid if the area extends beyond the root container. What happens to invalid documents is not specified.

**Comment by nigelmegitt** [comment]
By the way, one more data point here is that what I am proposing is coincident with what is in the TTML2 WD, so the transition from activeArea in IMSC 1 to activeArea in IMSC 2 will be easier if we adopt my proposal.

**Comment by nigelmegitt** [comment]
I get that this is frustrating because we discussed this and thought we had agreed on the current text for activeArea, but I have one more proposal that will:

1. Define permitted values
2. Define semantics for all permitted values
3. Provide a way forward also for an equivalent feature in TTML2

The proposal is to modify the syntax of `ittp:activeArea` as follows, and to raise an issue to make the equivalent change to `ttp:activeArea` in TTML2.

The new syntax would use a two percentage value "position" in place of the "origin" for the first two components of the parameter value. This proposal has the feature that all 4 values can be in the range 0-100% legally and generate a semantically sensible outcome in which the area specified is wholly within the root container region.

For reference see https://www.w3.org/TR/ttml2/#style-attribute-position and https://www.w3.org/TR/ttml2/#style-value-position - in this case we would constrain the position to be of the two non-negative percentage value form, i.e. where the first coordinate offsets from the left edge and the second from the top.

Then we have `"pos-x pos-y width height"` and the translation to origin `x y` coordinates, if needed, would be:

`x = pos-x * (1 - width/100)`
`y = pos-y * (1 - height/100)`

This is based on a simplified subset of the CSS background-position semantics defined at https://www.w3.org/TR/css3-background/#the-background-position as is TTML2's `<position>`.

**Comment by skynavga** [comment]
This sounds more like a semantic change than a syntax change, since nothing
changes at the lexical level.

**Comment by nigelmegitt** [comment]
I'm not sure how valuable it is to get into the definitions of semantic vs syntactic here. I agree that lexically the format is the same, however semantically the result is also the same, i.e. a rectangle defined within the root container region. However the processing required to arrive at that result differs.

This also provide a more elegant path to TTML2 compatibility - note that part of the proposal is to change the equivalent feature in TTML2, which aligns it with the move from origin based coordinates to position based ones, since `tts:origin` is deprecated in TTML2. It seems strange at the moment that we are introducing a new area feature into TTML2 that uses a deprecated approach to defining position.

**Comment by skynavga** [comment]
On Wed, Feb 15, 2017 at 1:49 AM, Nigel Megitt <notifications@github.com>
wrote:

> I'm not sure how valuable it is to get into the definitions of semantic vs
> syntactic here. I agree that lexically the format is the same, however
> semantically the result is also the same, i.e. a rectangle defined within
> the root container region. However the processing required to arrive at
> that result differs.
>
> This also provide a more elegant path to TTML2 compatibility - note that
> part of the proposal is to change the equivalent feature in TTML2, which
> aligns it with the move from origin based coordinates to position based
> ones, since tts:origin is deprecated in TTML2. It seems strange at the
> moment that we are introducing a new area feature into TTML2 that uses a
> deprecated approach to defining position.
>
I agree on this last point, and considered the use of position instead of
origin when originally drafting the text; but had decided then to go ahead
with what had been proposed.

**Comment by palemieux** [comment]
@nigelmegitt Can you prepare a PR for consideration during the call tomorrow? Please use a symbol other than `pos-x` since the `-` could be interpreted as a minus sign.

**Comment by nigelmegitt** [comment]
@palemieux done, in limited time, so a review would be appreciated.
