### ISSUE TITLE
Copy referenced schema to the schema directory for ease of validation

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#212]
Currently the schema depends on some external schema such as `xml.xsd` that are not in the repository. I would like to copy them into the repository for ease of reference when using validating XML processors, and modify the `import` statements to reference the filename explicitly by adding a `schemaLocation` attribute.

I am happy to generate a pull request for this myself if nobody else wants to do it!

**Comment by palemieux** [comment]
> I would like to copy them into the repository for ease of reference when using validating XML processors, and
> modify the import statements to reference the filename explicitly by adding a schemaLocation attribute.

Including a schemaLocation in standard definitions is undesirable in my experience since (i) validators might already have a local repository of XSDs, e.g. mapped to namespaces through a catalog, (ii) it forces duplication of XSDs (which is troublesome if an XSD changes) and (iii) requires a particular file naming convention and directory structure.

**Comment by nigelmegitt** [comment]
Well the schema is non-normative and this is already done in the TTML1 schema for example, which includes `xml.xsd`, which by the way is stable. As far as I'm concerned they can be a flat list of XSDs and do not need any particular directory structure. They just have to be consistently named with what is in the imsc schema documents.

**Comment by palemieux** [comment]
@nigelmegitt How do you address (ii) above?

**Comment by nigelmegitt** [comment]
The schema that are referenced are stable; if they were to change then we would not adopt new ones without a spec update anyway. So duplication is actually reasonable here.

**Comment by palemieux** [comment]
Right. Effects are benign if only xml.xsd is included. This however sets a precedent which will be difficult to change in the future, and duplication is bad practice. That said, I am not going to object if group consensus is to go down that path.

**Comment by mikedo** [comment]
Be sure to get the latest xml.xsd from the namespace link.

**Comment by palemieux** [comment]
@nigelmegitt Does this mean that all XSD referenced in `imsc1-all.xsd` also need to be imported?

**Comment by nigelmegitt** [comment]
> Does this mean that all XSD referenced in imsc1-all.xsd also need to be imported?

Yes that would be my preference. The list is currently:

```xml
  <!-- TTML schemas can be found at http://www.w3.org/2013/09/ttml1/xsd/schema.zip -->
  
  <xs:import namespace="http://www.w3.org/ns/ttml"/>
  <xs:import namespace="http://www.w3.org/ns/ttml#parameter"/>
  <xs:import namespace="http://www.w3.org/ns/ttml#styling"/>
  <xs:import namespace="http://www.w3.org/ns/ttml#metadata"/>
  
  <!-- SMPTE-TT schemas can be found at www.smpte-ra.org/schemas/2052-1/2010/smpte-tt.xsd -->
  
  <xs:import namespace="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt"/>
  
  <!-- EBU-TT-D schemas can be found at https://github.com/ebu/ebu-tt-d-xsd/tree/editors-draft -->
  
  <xs:import namespace="urn:ebu:tt:style"/>
  <xs:import namespace="urn:ebu:tt:metadata"/>
```

I'm not sure what state the smpte-tt or ebu-tt schemas are in for the purpose of importing; I would certainly consider defining bespoke XSDs only for the parts of those namespaces that are referenced by IMSC1, and referencing those locally.

**Comment by nigelmegitt** [comment]
Closing this as there is an accepted mechanism for dereferencing namespaces to schemas, even if I haven't personally managed to make it work.
