### ISSUE TITLE
Attribute syntax definition: missing spaces

### ISSUE THREAD

**Issue by spoeschel** [w3c/imsc#221]
The `ittp:aspectRatio` attribute uses spaces to separate numerator and denominator within the attribute value (e.g. `ittp:aspectRatio="4 3"`). However the attribute definition lacks the space character `" "`.

The `ittp:activeArea` attribute uses spaces to separate adjacent components within the attribute value (e.g. `ittp:activeArea="50% 50% 80% 80%"`). The attribute definition here lacks the space character `" "` as well.

**Comment by nigelmegitt** [comment]
This is true however it matches the style of definitions in TTML1 - see for example [tts:extent](https://www.w3.org/TR/ttml1/#style-attribute-extent). There is further information on this at w3c/ttml2#191 and w3c/ttml2#190. I do not believe we need to make a change now to IMSC 1 for this, however if we are going to then the change would be to introduce the term `lwsp` as defined in TTML1 between the values.

**Comment by nigelmegitt** [comment]
> Doesn't XML essentially normalize lwsp sequences to a single U+0020?

The point I think is that there is no delimiter explicitly mentioned, just an implicit one, so the requirement for a lwsp sequence to normalise is not clear. This is the same in TTML1SE so we are just continuing the same pattern.

I do agree that it would be an improvement in both cases to mention lwsp where it is intended, and this is intended in TTML. By the way, [TTML1SE §8.2](https://www.w3.org/TR/ttml1/#styling-attribute-vocabulary) says:

> Unless explicitly stated otherwise, linear white-space (LWSP) must appear between adjacent non-terminal components of a value of a TT Style or TT Style Extension Property value unless some other delimiter is permitted and used.

Similar language exists in §6.2 for Parameter Attribute Vocabulary.

This spirit is also intended here. It possibly needs to be made explicit if it is not clear.

**Comment by palemieux** [comment]
@nigelmegitt To make sure we have the same understanding of the current situation:

- TTML 1SE states that _linear white-space (LWSP) must appear between adjacent non-terminal components of a value of a TT Style or TT Style Extension Property value unless some other delimiter is permitted and used._

- These LWSPs are not shown in the syntax definitions

- by the time the attribute value makes it to the processor, all LWSPs have been normalized to a single U+0020. In other words, processors can safely assume that only ever one U+0020 will separate _adjacent non-terminal components_

**Comment by nigelmegitt** [comment]
@palemieux That is correct, however this issue is not about those attributes defined in TTML but the ones defined in IMSC1.0.1 where no statement is made about LWSP.

**Comment by nigelmegitt** [comment]
By the way, I think it is reasonable to consider this issue within wide review feedback.

**Comment by palemieux** [comment]
@nigelmegitt My understanding is the same as yours. I have scheduled the ticket for CR.

**Comment by skynavga** [comment]
Sorry for the delayed comments, but this proposed change is entirely unnecessary. It is unreasonable to suggest that IMSC would use or imply a different generic rule regarding the necessity of a delimiter between non-terminals in a value syntax specification. This most definitely should be covered by the existing language in TTML1 6.2:

>Unless explicitly stated otherwise, linear white-space (LWSP) must appear between adjacent non-terminal components of a TT Parameter value unless some other delimiter is permitted and used.

At most, you may simply add a note or a normative sentence that refers to this language as also applying to ittp:* attributes.
