### ISSUE TITLE
Clarification: Which mix of timing syntax is NOT recommended

### ISSUE THREAD

**Issue by tairt** [w3c/imsc#223]
IMSC1 recommends using one syntax for timing ([Section 6.11, Common Constraints, Features, #timing](https://www.w3.org/TR/ttml-imsc1/#common-features)) 

> All time expressions within a Document Instance should use the same syntax, either clock-time or offset-time.

Does this mean that "f" and "ms" approach can be mixed? Both can be offset time. In other words: Is the current syntax **not** recommended or is this not in scope of the constraint cited above:

```xml
<p begin="80ms" end="50f">..</p>
```

**Comment by palemieux** [comment]
> Does this mean that "f" and "ms" approach can be mixed?

This is my read as currently drafted.

**Comment by tairt** [comment]
Ok! Although I do not understand the logic behind it (it is not less confusing to mix "ms", "ticks" and "frames" than to mix clock-time and offset-time), I close this issue. If somebody has a different interpretation he/she needs to re-open.

Thanks @palemieux for quick response.
