### ISSUE TITLE
Create tests for CR exit criteria

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#226]
Create tests suitable for CR exit criteria, e.g. as discussed in Meeting 2017-04-13:

1. Not failing when processing a document with ittp:activeArea present
2. (perhaps) indicating on some console output the found value of ittp:activeArea.
3. Successful presentation of the lineGap style as per the example in the spec, in other words turning that example into a test vector.

**Comment by palemieux** [comment]
Implemented at 4f199de739945656838423d18ff8df6235be4277

**Comment by palemieux** [comment]
@nigelmegitt Can you review https://github.com/w3c/imsc/commit/4f199de739945656838423d18ff8df6235be4277 ?

**Comment by nigelmegitt** [comment]
@palemieux looks good mostly - I had a question and a proposal. Do we have a summary changes text file yet? I could not see one in that commit, and am not sure if we have already made one.

**Comment by palemieux** [comment]
> Do we have a summary changes text file yet? I could not see one in that commit, and am not sure if we have already made one.

See substantive-changes-summary.txt

**Comment by nigelmegitt** [comment]
> See substantive-changes-summary.txt

OK but that is more sparse than I'm expecting. For convenience, that document is at https://www.w3.org/TR/ttml-imsc1.0.1/substantive-changes-summary.txt 

I think we will be expected to provide a changes since 1.0 Rec also.

**Comment by palemieux** [comment]
> I think we will be expected to provide a changes since 1.0 Rec also.

As you may recall from the earlier TTWG discussions, this will be provided by a diff against 1.0 (see SotD at https://www.w3.org/TR/ttml-imsc1.0.1/)

**Comment by palemieux** [comment]
> OK but that is more sparse than I'm expecting.

I plan to update the file right before the next WD publication. 

https://github.com/w3c/imsc/commit/4f199de739945656838423d18ff8df6235be4277 was intended to cover the exit criteria only :)

**Comment by palemieux** [comment]
See #244 for substantive-changes-summary.txt
