### ISSUE TITLE
Determination of the color in leading in tts:fillLineGap

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#228]
From https://lists.w3.org/Archives/Public/public-tt/2017May/0018.html

>The fillLineGap attribute is intended to widen background color
filling of letters to line gap. Fig.1 of the draft looks filling the 
background in a color of descent in the upper line to the center of 
leading, and the other half of leading is filled in a color of ascent 
in the next line. We are not sure this is the typical case for 
determination of the color in leading. It is suggested to describe 
color determination algorithm, or to describe it is 
implementation-dependent.

**Comment by tairt** [comment]
I think there is a misunderstanding. Although it looks in the first picture of figure 1 like one gap, one part from it belongs to the linea rea of row1 and the other belongs to the line area of row 2. It maybe good to indicate the line areas in the two pictures with dotted lines.

**Comment by palemieux** [comment]
@tairt Can you generate an image with the line? I will add it.

**Comment by tairt** [comment]
Yes, I will do it.

**Comment by tairt** [comment]
@palemieux See attached a proposed picture. The light blue box indicates the line-area.

![filllinegap-sample1-with-linearea](https://cloud.githubusercontent.com/assets/4597762/26368947/79f86d04-3ff3-11e7-96df-b7be6d2fc77b.png)

**Comment by palemieux** [comment]
@tairt Is there a third blue line missing?

**Comment by tairt** [comment]
@palemieux For simplicity I indicated the line area only for the second row, but feel free to add more (note that it is a box that has also blue vertical lines...although they do not come out very well).

**Comment by palemieux** [comment]
Closed per https://lists.w3.org/Archives/Public/public-tt/2017Jun/0111.html
