### ISSUE TITLE
imsc1-all.xsd has a bad pointer for SMPTE-TT schemas

### ISSUE THREAD

**Issue by mikedo** [w3c/imsc#235]
SMPTE schemas are in a zip file related to the standard in the IEEE store as part of SMPTE ST 2052-1:2013 found at http://ieeexplore.ieee.org/document/7291854/media

**Comment by mikedo** [comment]
In researching this further, I find that IMSC1 references a non-specific version of the ST2052-1 spec and requires the "2010" namespace.  The 2010 namespace schema is no longer available at SMPTE (only 2013).  I think I will author and contribute to W3C a 2010 smpte:backgroundImage schema (all that's needed from SMPTE and also compatible with 2013).

**Comment by skynavga** [comment]
The 2010 schemas used by TTV can be found here:

https://github.com/skynav/ttt/tree/master/ttt-ttv/src/main/resources/com/skynav/ttv/xsd/smpte/2010

**Comment by nigelmegitt** [comment]
Meeting 2017-06-08: Agreed to request clarification from SMPTE and then potentially (depending on the response) add clarification text to IMSC to explain that `backgroundImage` is supposed to take a `xs:anyURI` (if that is confirmed).

**Comment by nigelmegitt** [comment]
Meeting 2017-06-22: See the incoming liaison from SMPTE at https://lists.w3.org/Archives/Public/public-tt/2017Jun/0084.html - this schema can simply be included in the informative IMSC schemas now. @palemieux to add a new milestone for this work.

**Comment by palemieux** [comment]
@tmichel07 See modifications at https://github.com/w3c/imsc/commit/51bff7794311b7cb87f4072ab5a992cf61822e3c to be applied to https://www.w3.org/TR/2016/REC-ttml-imsc1-20160421/xml-schemas/imsc1-all.xsd
