### ISSUE TITLE
Change itts:fillLineGap to ittp:fillLineGap.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#238]
Suggest that itts:fillLineGap be changed to a parameter attribute ittp:fillLineGap, since it is probably only going to be a constant inherited value in a given document, i.e., I would not expect it to vary between paragraphs. This will also make it easier to map to the ttp:fillLineGap parameter attribute proposed [1] for TTML2.

[1] https://github.com/w3c/ttml2/pull/346

**Comment by nigelmegitt** [comment]
[Meeting 2017-06-01] Group recalls that we discussed this and agreed to use a style attribute in London.

**Comment by skynavga** [comment]
Even though I have doubts about the complexity vs tradeoff functionality in this case, and believe that a document wide parameter is more practical, I am yielding to the group's decision to retain this as a content specific style, and therefore closing.
