### ISSUE TITLE
Requirement to support certain Code Point

### ISSUE THREAD

**Issue by tairt** [w3c/imsc#241]
As there is a discussion recently about Reference Fonts in IMSC1, I would like to clarify, if a presentation processor **SHALL** have a font available for all codepoints listed in Annex B (https://www.w3.org/TR/ttml-imsc1/#recommended-unicode-code-points-per-language).

Section 7.3 states:

> When rendering codepoints matching one of the combinations of computed font family and codepoints listed in A. Reference Fonts, a processor **shall** use a font that generates a glyph sequence whose dimension is substantially identical to the glyph sequence that would have been generated by one of the specified reference fonts.

Regarding codepoints Annex A. points to Annex B (without making an exception). 

My reading is that implicitly there must be font support for all codepoints in Annex B. It is the minimum condition to generate an identical glyph sequence as in the reference fonts.

I could also see why there may be other interpretations (e.g. because ANNEX B has only "recommended" in the title). But from my interpretation the normative text is clear. 

One other observation: people may also have problems in reading the statements for table 2.

> Table 2 specifies supplementary character set that have proven useful in captioning and subtitling applications for a number of selected languages. Table 2 is non-exhaustive, and will be extended as needs arise.

Especially the addition that this table may be extended could lead to the conclusion that support for table 2 characters is more a recommendation then a strict normative requirement.

**Comment by nigelmegitt** [comment]
I have also heard differing interpretations. Also since there is this section:

>7.2 Recommended Character Sets
>
>A Document Instance should be authored using characters selected from the sets specified in B. Recommended Character Sets.

which seems to suggest that there is no processor requirement to support any specific set of code points at all.

**Comment by skynavga** [comment]
On Fri, Jun 2, 2017 at 8:05 AM, Nigel Megitt <notifications@github.com>
wrote:

> I have also heard differing interpretations. Also since there is this
> section:
>
> 7.2 Recommended Character Sets
>
> A Document Instance should be authored using characters selected from the
> sets specified in B. Recommended Character Sets.
>
> which seems to suggest that there is no processor requirement to support
> any specific set of code points at all.
>
From the view of TTML, that is true.

**Comment by palemieux** [comment]
> My reading is that implicitly there must be font support for all codepoints in Annex B. It is the minimum condition to generate an identical glyph sequence as in the reference fonts.

This is not my read.

[Section 7.3](https://www.w3.org/TR/ttml-imsc1/#reference-fonts-1) specifies that:

_When rendering codepoints matching one of the combinations of computed font family and codepoints listed in A. Reference Fonts, a processor shall use a font that generates a glyph sequence whose dimension is substantially identical to the glyph sequence that would have been generated by one of the specified reference fonts._

This does not require the processor to support all codepoints specified for the Reference Fonts (as defined in [Annex A](https://www.w3.org/TR/ttml-imsc1/#reference-fonts)).

It only requires the processor to use the metrics of the codepoints as implemented by the Reference Fonts (as defined in Annex A) **if** the processor supports the codepoint.

A processor that claims to support a particular language is encouraged (but not required) to support a specified set of codepoints per [Annex B](https://www.w3.org/TR/ttml-imsc1/#recommended-unicode-code-points-per-language) .

**Comment by palemieux** [comment]
> Especially the addition that this table may be extended could lead to the conclusion that support for table 2 characters is more a recommendation then a strict normative requirement.

Yes, Annex B implicitly encourages (but does not require) a processor that claims to support a particular language to support a specified set of codepoints.

**Comment by tairt** [comment]
Thanks @palemieux for the clarification!

> It only requires the processor to use the metrics of the codepoints as implemented by the Reference Fonts (as defined in Annex A) if the processor supports the codepoint.

At least there could be a "mis-reading" of the current spec text. The condition where the SHALL applies is:

> When rendering codepoints matching one of the combinations of computed font family and codepoints listed in A. Reference Fonts

If a processor does not have a font available for a specific codepoint it will be often nonetheless render it with as substitute glyph. In this case the situation of rendering the codepoint is there and also the computed font-family could be e.g. `monospaceSerif` and the codepoint could be listed in Annex A (e.g. `U+20AC `, the Euro Sign). So it seems that all condition are met to

>  use a font that generates a glyph sequence whose dimension is substantially identical to the glyph sequence that would have been generated by one of the specified reference fonts.

Possibly some text could be added the condition is that the codepoint is supported.

**Comment by nigelmegitt** [comment]
I agree with all the above! However I think it is unlikely that the glyph sequence dimension requirement could be met in practice except by supporting the glyphs. A fallback glyph (especially if the same one is used for multiple code points, such as a ▯ or similar) would very likely not meet the requirements in all cases. This means that the glyph sequence dimension requirement acts as a proxy requirement for code point support in the reference fonts. 

I think the wording in IMSC §7.2 and §7.3 could certainly be improved. The current way that in one case document authors are encouraged only to use certain code points and in the other processors are required to meet glyph sequence dimension requirements is rather confusing.

It would be helpful to separate out the concerns of glyph sequence dimensions and code point support if possible, or if that is not genuinely possible, then to make them clearly part of the same section.

**Comment by palemieux** [comment]
I plan to generate a PR that provides clarification as stated in https://github.com/w3c/imsc/issues/241#issuecomment-305868266
