### ISSUE TITLE
Recommended character sets considered harmful

### ISSUE THREAD

**Issue by aphillips** [w3c/imsc#243]
This is [I18N WG issue 420](https://github.com/w3c/i18n-activity/issues/420)

7.2 Recommended Character Sets
https://www.w3.org/TR/ttml-imsc1.0.1/#recommended-character-sets

> A Document Instance SHOULD be authored using characters selected from the sets specified in B. Recommended Character Sets.

This text and the text in _Appendix B_ is intended to describe content restrictions that authors should observe when writing captions and subtitles in a TTML document. There are a number of problems with this:

1. Numerous important languages and their scripts, most notably the Chinese/Japanese/Korean scripts, but also, for example, the scripts of South Asia/India, the scripts of Southeast Asia, and so forth are completely omitted. These comprise large audiences who might well use TTML and IMSC, but who are excluded from consideration.
2. The reference materials that do exist have gaps in coverage or are uneven in the recommended glyph set supported by the fonts. For example, only `pt` and `es` include the currency symbols other than $ and Euro. Why this is the case is not clear. It seems strangely inconsistent.
3. Rendering systems generally use font fallback to provide coverage with high-enough quality for multiple scripts rather than using a single font or font collection. If the goal is to describe limited capacity devices, such as a display with only a single or small number of hardcoded fonts for captioning built in, it would be more useful to describe a few "profiles" for minimum glyph sets than trying to break it out by language. Even then, I'd be concerned that we're artificially promoting to implementers specific language support rather than providing useful guidance to authors. In short, I don't think that, as structured, this text accomplishes its aim.

**Comment by aphillips** [comment]
Please add the i18n-comment label. Thanks.

**Comment by palemieux** [comment]
@aphillips  Before delving in specifics.

> Numerous important languages and their scripts, most notably the Chinese/Japanese/Korean scripts, but also, for example, the scripts of South Asia/India, the scripts of Southeast Asia, and so forth are completely omitted. 

The character sets of Annex B are a superset of the CLDR character sets. Are you suggesting that CLDR does not provide an adequate basis?

**Comment by aphillips** [comment]
@palemieux Not exactly. The part you quote of my comment refers to the fact that: 

> Table 2 is non-exhaustive, and will be extended as needs arise.

The "recommended character sets" support some (but not all) languages written in Latin, Cyrillic, Greek, Arabic, and Hebrew scripts, but noticeably omit other widely used scripts or languages. 

CLDR is as good starting point for defining "minimal support" for a given language as is available, but as an implementer or content author I wouldn't be sure what to do with the lists. Our WG was concerned that these character lists would become in some way normative to IMSC implementations rather than advisory.

**Comment by palemieux** [comment]
> but as an implementer or content author I wouldn't be sure what to do with the lists.

The introductory paragraphs to Annex B clearly specifies recommendation for authors, esp. that Table 2 is not the only one to consider:

```
an author should choose characters from the set resulting from the union of the following sets:
* the main exemplar character set specified for the language in [CLDR] as well as any corresponding uppercase characters as specified in [UNICODE]; and
* the punctuation exemplar character set specified for the language in [CLDR];
* the digits and symbols included in all numberSystems specified for the language in [CLDR];
* the common character set specified in Table 1; and
* supplementary characters specified for the language in Table 2, if any.
```

In fact, the long-term objective is to hopefully defer to CLDR entirely, and remove Tables 1 and 2 -- see [issue 8915](http://unicode.org/cldr/trac/ticket/8915).

> The "recommended character sets" [...] noticeably omit other widely used scripts or languages.

The entire CLDR set is included through the normative paragraph above.... or are you suggesting that _widely used scripts or languages_ are missing from CLDR? If so, which ones?

In any event, Annex B does not impose any constraint and/or recommendations on languages not included. Perhaps this needs to be clarified?

> Our WG was concerned that these character lists would become in some way normative to IMSC implementations rather than advisory.

The intent is merely to provide guidance and not to limit implementations -- how can this be made clearer? Note that the current text is only a recommendation (_authors SHOULD_).

**Comment by nigelmegitt** [comment]
Meeting 2017-06-22: @aphillips ping - we are not sure if we need to take any action here: what is your thought about https://github.com/w3c/imsc/issues/243#issuecomment-305999775 ?
