### ISSUE TITLE
SDP-US is listed as a normative reference, but it is not

### ISSUE THREAD

**Issue by mikedo** [w3c/imsc#246]
SDP-US is not cited in normative text and is not essential to practicing IMSC1.  Move to informative references.

**Comment by palemieux** [comment]
SDP-US is referenced in the clause: _the Document Instance also conforms to [ttml10-sdp-us], in which case the ttp:profile attribute should not be present_.

... so technically one needs to read SDP-US to implement the `should`.

**Comment by mikedo** [comment]
The leading phrase is a rationale, not a condition upon which one must read SDP-US. There is nothing in IMSC1 that requires one to read SDP-US to implement IMSC1.

**Comment by mikedo** [comment]
The sentence in question is stating only that if there is a *desire* to conform to SDP-US what might need to be about it already codified in SDP-US.  Conformance to SDP-US is unrelated to IMSC1 and does not belong in IMSC1.

Since there is no information in SDP-US needed to implement IMSC1 (i.e. it is not "essential") the presence of "should" in this sentence is just an unfortunate choice of words, not a defacto conformance provision.

This sentence should be removed, or if kept, changed to be more clearly a statement of fact of the form, "Note: If concurrent conformance to SDP-US is desired, then ttp:profile cannot be set." Or something like that.

Although modifying a sentence with a conformance term in it may be a red flag at this stage of v1.0.1, in this case, fixing it is editorial, since it has zero impact on IMSC1 conformance.
