### ISSUE TITLE
Publish CR

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#248]
* [x] upload ./xml-schemas to https://www.w3.org/AudioVideo/TT/IMSC/ttml-imsc1.0.1/xml-schemas/
* [x] upload diff from first WD to ./diff.html

**Comment by tmichel07** [comment]
Done,

I have moved the imsc schema from github repo to final detination.
https://www.w3.org/AudioVideo/TT/IMSC/ttml-imsc1.0.1/xml-schemas/



Thierry
