### ISSUE TITLE
Mixed units in tts:origin and tts:extent value

### ISSUE THREAD

**Issue by spoeschel** [w3c/imsc#249]
I wonder whether the mixing of different units (e.g. `px` and `%`) within the same attribute value is allowed for `tts:origin` and `tts:extent` in IMSC1, e.g. usage of the value `10% 200px`.

My understanding is that according to the table in §7.4, it is is allowed for `tts:origin`, as for the `#origin` feature the "Additional provisions" column states:

"The tts:origin attribute SHALL use px units or "percentage" representation, and SHALL NOT use em units."

For `tts:extent` in contrast it is not allowed according to my understanding, as that table column for the `#extent-region` feature states:

"The tts:extent attribute SHALL be present on all region elements, where it SHALL use either px units or "percentage" syntax."

Is this interpretation correct? As my expectation was that is it premitted either for both attributes or for neither of them.

**Comment by palemieux** [comment]
I interpret the specification as allowing any combination of `%` and `px` units on both `tts:origin` and `tts:extent` on `region`

**Comment by skynavga** [comment]
The only constraint requiring both values to employ the same units is with
TTML1's use of tts:extent on the root tt element, where both must be px.

**Comment by spoeschel** [comment]
Hmm, so what meaning has the word "either" in the `tts:extent` definition? Doesn't it prohibit that `px` and `%` are used together in the same attribute value?

**Comment by palemieux** [comment]
> Hmm, so what meaning has the word "either" in the tts:extent definition?

No meaning intended. I think we could remove it if it causes confusion.

**Comment by nigelmegitt** [comment]
Really? So the intent was to permit something like:

```xml
<region tts:extent="555px 10%" tts:origin="20px 80%" xml:id="weirdRegion"/>
```

Is there a use case for this? If so, what is it? Do we have any data points of it being used? What would be the impact if we constrained it? (by the way, EBU-TT-D constrains it to only use two % values)

@spoeschel what made you ask the question, out of interest?

**Comment by palemieux** [comment]
> Really? So the intent was to permit something like:

Yes. It looks like it.

> What would be the impact if we constrained it?

It is permitted today, so cannot be constrained without breaking conformance.

**Comment by skynavga** [comment]
Clearly the use of either is wrong. As one would read it to mean that both
are px or both are %, when a mixture is permitted by TTML1, though I don't
know if the intention of IMSC1 is to restrict TTML1 here.

**Comment by spoeschel** [comment]
> Is there a use case for this?

I can hardly imagine such a case.

> @spoeschel what made you ask the question, out of interest?

@nigelmegitt I just read through the IMSC1 spec, and as `tts:origin` and `tts:extent` are used to describe the same rectangle of a region's extent, it looked strange that the allowed use of units within that attributes seem to differ.

**Comment by skynavga** [comment]
The "CSS Working Group" ?!

**Comment by nigelmegitt** [comment]
> The "CSS Working Group" ?!

Yes, I am about to propose a change to github-bot to just say "The Working Group" in the absence of anything better. Properly the group should be associated with the channel in the config.

**Comment by nigelmegitt** [comment]
https://github.com/dbaron/wgmeeting-github-ircbot/issues/14

**Comment by spoeschel** [comment]
Thanks!
