### ISSUE TITLE
displayAlign feature problem

### ISSUE THREAD

**Issue by cconcolato** [w3c/imsc#256]
In IMSCvNext, the text profile permits #displayAlign but does not permit its components #displayAlign-region
#displayAlign-relative
Can you clarify?

**Comment by cconcolato** [comment]
Also, #displayAlign-version-2 references #displayAlign-content which is called #displayAlign-block. Only one name should be used, also in TTML2.

**Comment by palemieux** [comment]
> Can you clarify?

This is a bug, #displayAlign-region and #displayAlign-relative should be permitted.

> Also, #displayAlign-version-2 references #displayAlign-content which is called #displayAlign-block. Only one name should be used, also in TTML2.

I have filed https://github.com/w3c/ttml2/issues/456
