### ISSUE TITLE
Nested ruby should not be allowed

### ISSUE THREAD

**Issue by cconcolato** [w3c/imsc#257]
In IMSCvNext, the current text allows nested ruby because the #ruby feature is permitted and this one is defined as:

> A TTML presentation processor supports the #ruby feature if it implements presentation semantic support for all defined values of the tts:ruby attribute in both nested and non-nested contexts.

The #ruby feature should be prohibited, and the #ruby-non-nested should remain permitted.

**Comment by palemieux** [comment]
@cconcolato Can you confirm that nested ruby annotations are not used for captions/subtitles?

**Comment by cconcolato** [comment]
At least, on our side, we do not use them.

**Comment by palemieux** [comment]
Ok. Changing since the detailed requirement came from Netflix.
