### ISSUE TITLE
IMSCvNext profile signaling and version

### ISSUE THREAD

**Issue by cconcolato** [w3c/imsc#261]
Section 7.8 Profile Signaling does not mention how the ttp:version attribute should be used. Some recommendations would help, maybe using ttp:version=1 when IMSC1 compatibility is needed.

**Comment by nigelmegitt** [comment]
Since an IMSCv1 document will likely not have been authored with TTML2 in mind, a missing `ttp:version` attribute is one signal that the document might be an IMSC1 document. Of course there are also the profile identifier(s) to be worried about here too, and the use of TTML2 syntax.

**Comment by palemieux** [comment]
Blocked by https://github.com/w3c/ttml2/issues/435

In the meantime, see #267 for an approach to signaling that does not require `ttp:version`.
