### ISSUE TITLE
Region constraints are the same as in IMSCvNext

### ISSUE THREAD

**Issue by cconcolato** [w3c/imsc#262]
Section 7.10.1 seems to be a copy/paste of IMSCv1.0.1 6.8. It should be made explicit in the IMSCvNext spec.

**Comment by cconcolato** [comment]
Similarly for other similar copy/paste sections such as: Referenced Fonts, Recommended Character Sets ...

**Comment by palemieux** [comment]
@cconcolato What do you mean by _It should be made explicit in the IMSCvNext spec_?

**Comment by palemieux** [comment]
Propose to add reference to Annex L (Substantive differences wrt IMSC1.0.1) at the beginning of the document
