### ISSUE TITLE
ttp:displayAspectRatio is prohibited

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#273]
IMSC1 uses `ittp:aspectRatio` instead.

See https://github.com/w3c/ttml2/issues/477

**Comment by nigelmegitt** [comment]
Netflix has objected to this Resolution, requesting:

* Mark `ittp:aspectRatio` as deprecated in IMSC 1.1, referencing the definition in IMSC 1.0.1
* Use `ttp:displayAspectRatio` in IMSC 1.1, the feature as defined in TTML2
