### ISSUE TITLE
Should ittp:activeArea be deprecated?

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#275]
Depends on https://github.com/w3c/ttml2/issues/428

**Comment by nigelmegitt** [comment]
Netflix has objected to this Resolution, requesting:

* Mark `ittp:activeArea` as deprecated in IMSC 1.1, referencing the definition in IMSC 1.0.1
* Use `ttp:activeArea` defined in TTML2
* In IMSC 1.1 restrict the syntax to two component values aligned with ittp:activeArea
