### ISSUE TITLE
Should itts:forcedDisplay be deprecated?

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#279]
Depends on https://github.com/w3c/ttml2/issues/482

**Comment by palemieux** [comment]
TTML2 implements functionality equivalent to `itts:forcedDisplay` using the `condition` feature. See https://github.com/w3c/ttml2/issues/482#issuecomment-342324353

**Comment by nigelmegitt** [comment]
Netflix has objected to this Resolution, requesting:

* Mark `itts:forcedDisplay` as deprecated in IMSC 1.1, referencing the definition in IMSC 1.0.1
* Use `condition` and `tts:visibility` in IMSC 1.1, as defined in TTML2
* Constrain `condition` in IMSC 1.1 to make it easy to implement (_ed_: needs further detail)
