### ISSUE TITLE
Improve text of I.4 SMPTE-TT (SMPTE ST 2052-1)

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#312]
The appendix does not take into account that IMSC1.1 is based on TTML2, whereas SMPTE ST 2052-1 is based on TTML1.

**Comment by nigelmegitt** [comment]
It looks okay right now, on a quick scan, particularly noting the resolution to require DFXP support in TTML2. What are the deltas that need to be applied?

**Comment by palemieux** [comment]
I would think that the following:

> This specification defines practical constraints on [SMPTE2052-1], supplemented by a few extensions defined at F. Extensions. These constraints and extensions are intended to reflect industry practice.

should be rephrased to

> This specification defines practical constraints on [SMPTE2052-1], supplemented by extensions defined herein and TTML2 features . These constraints and extensions are intended to reflect industry practice.

... but if you think the current text is ok, I am happy to close the issue :)

**Comment by nigelmegitt** [comment]
Thanks, that change looks like a worthwhile improvement to me.
