### ISSUE TITLE
APA comment: Improve introduction

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#315]
From https://lists.w3.org/Archives/Public/public-tt/2018Jan/0270.html

While we appreciate that TTML Profiles for Internet Media Subtitles and Captions 1.1 <https://www.w3.org/TR/ttml-imsc1.1/>  is depending on Timed Text Markup Language 2 (TTML2) <https://www.w3.org/TR/ttml2/> , it should still include an introduction that guides the reader to a better understanding of its content.  Such an introduction could respond to the following questions:

a.	Why are profiles needed for text-only and image-only captions/subtitles?
b.	What are typical use cases for a image-only captions/subtitles?
c.	What is the purpose of a presentation processor, and a transformation processor?

**Comment by palemieux** [comment]
Proposed disposition: WR-resolved (see PR).
