### ISSUE TITLE
APA comment: specify association between image and text profile documents

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#318]
From https://lists.w3.org/Archives/Public/public-tt/2018Jan/0270.html

Section 5.1 General. The method of associating a text profile document instance with an image profile document instance should be specified for interoperability reasons, and not be left open to the specific implementation.  Also, the association should be in both ways, i.e. also from the image profile document instance to the text profile document instance.

**Comment by palemieux** [comment]
> The method of associating a text profile document instance with an image profile document instance should be specified for interoperability reasons, 

The method to signal the characteristics of a subtitle track (language, image vs text, caption vs subtitle, etc.) depends on the container or transmission format, e.g. ISOBMFF (ISO/IEC 14496-12) and IMF (SMPTE ST 2067-2). This document is not the right place to catalog these methods.

**Comment by nigelmegitt** [comment]
Further, the relationship between document instances is in general an asset management task, and mixing that into the document contents itself in a normative way is not generally considered a good approach. The one thing that _could_ be useful is to add metadata indicating related media or alternate renderings. Such metadata are available for adoption and can be used in IMSC 1.1 with no modification to the specification required, for example EBU Tech3390 defines a wide variety of metadata useful in the production, archive and exchange domains.

It would be possible to add an informative note explaining that such metadata exist, but the risk is that we get an unending list of "please note my metadata schema too" requests - there are a _lot_ of metadata schema in the world!

**Comment by palemieux** [comment]
Proposed disposition: WR-reject
