### ISSUE TITLE
APA comment: permit font related features in Image profile

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#319]
From https://lists.w3.org/Archives/Public/public-tt/2018Jan/0270.html

Section 6 Supported Features and Extensions. All font-related features are prohibited for the image profile. This seems to be an unnecessary restriction if the image profile contains images in SVG format which could be rendered differently based on the author’s choice of font characteristics.

**Comment by palemieux** [comment]
IMSC 1.1 restricts images to PNG. Suggest deferring this to IMSCvNEXT.

**Comment by palemieux** [comment]
Proposed disposition: defer to IMSCvNEXT and WR-resolved-partial
