### ISSUE TITLE
Document structure of guidance for other profiles

### ISSUE THREAD

**Issue by mikedo** [w3c/imsc#331]
In sections 7.9.3 and 7.9.4, we have non-normative profile setting recommendations for other profiles (EBU-TT-D and SDP-US).  And, we have Annex I which contains related non-normative language for compatibility with various external profiles, including the two in 7.9. 

Conversely, we have normative profile settings for IMSC1 in 7.9.2 and related non-normative information in I.6.

All of this text would be a lot more readable if it were together. For example, Annex I talks about the relationship of the profiles to IMSC1.1, which is key to understanding why one might set the profile settings the way they are.

To improve readability, I propose the following restructuring of the sections: 1. move 7.9.3 and 7.9.4 to the ends of I.2 and I.3 respectively; and 2. move I.6 to the beginning of 7.9.2.

This also aggregates normative and non-normative text in the body (IMSC1) and the Annex (everything else) respectively.

**Comment by nigelmegitt** [comment]
This proposal is moving normative text to a non-normative section. It's a good idea to restructure to keep relevant information together, but I do not think we should change the normative/non-normative status of any bit of the spec when making this rearrangement.
