### ISSUE TITLE
typo in color syntax example

### ISSUE THREAD

**Issue by mikedo** [w3c/imsc#333]
In 8.4.1, there is: The named color "green" defined in [TTML2] is equivalent to the RGB triplet #008000 and is not full luminance. For full luminance green, an author can specify the RGB triplet #00ff00ff or the named color "lime".

The second "triplet" contains the alpha field, which distracts from the point.  Delete the trailing "ff". Also, these are not technically triplets. TTML2 calls them "RGB color triple". Change the names to this.

**Comment by anutin544** [comment]
Ok

**Comment by palemieux** [comment]
Fixed at https://github.com/w3c/imsc/pull/334
