### ISSUE TITLE
Feature #textOrientation-sideways-LR listed twice

### ISSUE THREAD

**Issue by spoeschel** [w3c/imsc#373]
In [§6](https://rawgit.com/w3c/imsc/IMSC1.1/imsc1/spec/ttml-ww-profiles.html#supported-features-and-extensions), the feature `#textOrientation-sideways-LR` is listed twice - with different dispositions for the Text profile.

**Comment by nigelmegitt** [comment]
Thanks for this @spoeschel , this is a substantive issue.

**Comment by nigelmegitt** [comment]
I've checked the definition of `#textOrientation` and it indeed appears that prohibiting `#textOrientation` prohibits all use of it, so permitting any subset of value makes no sense. Therefore there are two options:

1. Prohibit `#textOrientation-sideways-LR` in Text and Image profiles, and make no other change.
2. Make `#textOrientation` for Text profile partly permitted, and permit or prohibit `#textOrientation-sideways-LR` for Text Profile depending on what we actually need.

Permitting `#textOrientation` but prohibiting `#textOrientation-sideways-LR` means that the value for `tts:textOrientation` must be one of: `"mixed" | "sideways" | "upright"` and must not be one of: `"sidewaysLeft" | "sidewaysRight"`. There are no other values for this property defined in TTML2.

**Comment by palemieux** [comment]
> Prohibit #textOrientation-sideways-LR in Text and Image profiles, and make no other change.

I believe this was the intent since `#textOrientation` is not a requirement.
