### ISSUE TITLE
Yiddish in captions/subtitles

### ISSUE THREAD

**Issue by plehegar** [w3c/imsc#38]
From https://lists.w3.org/Archives/Public/public-tt/2015Jun/0001.html

> he (Hebrew)
> U+05B0 - U+05C3
> U+05D0 - U+05EA
> U+05F3 - U+05F4

http://en.wikipedia.org/wiki/Unicode_and_HTML_for_the_Hebrew_alphabet

Why are 05F0-05F2 excluded? (They're Yiddish, but is there a reason to
discriminate against Yiddish? Yiddish theater is real)

And, why would you exclude 059x, 05Ax, 05C4-05C7?

A perfectly reasonable thing to do w/ captions would be to caption
someone chanting from the Torah, or chanting a Haftarah which means
you'd need almost all of these (? is included in the text, but I
suppose you could argue for dropping from captions, I'd personally
include it, since omitting it would take more effort).

(raised by Pierre-Anthony Lemieux on 2015-06-11)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/391

**Comment by palemieux** [comment]
Propose closing this given that:

1. Unicode CLDR includes 'yi' locale data, which incorporated by reference in IMSC1
2. the objective is to ultimately replace Appendix B with a reference to a CLDR character set per http://unicode.org/cldr/trac/ticket/8915

**Comment by nigelmegitt** [comment]
> the objective is to ultimately replace Appendix B with a reference to a CLDR character set per http://unicode.org/cldr/trac/ticket/8915

We don't appear to have much momentum towards that objective @palemieux so in the short term I would advocate simply adding the missing codepoints.

**Comment by palemieux** [comment]
@nigelmegitt My point is that Yiddish is already included through CLDR, and that we should not try to modify the supplemental IMSC-specific tables.

**Comment by nigelmegitt** [comment]
@palemieux OK I guess we don't try to be exhaustive in listing all the languages, so that's reasonable.
