### ISSUE TITLE
Mention #extent-version-2 tts:extent value restriction in §6

### ISSUE THREAD

**Issue by spoeschel** [w3c/imsc#380]
The [feature `#extent-version-2`](https://w3c.github.io/ttml2/#feature-extent-version-2) refers to other features and at the same time enables the use of additional values for the `tts:extent` attribute. In IMSC 1.1, these values are then prohibited by [7.12.8](https://rawgit.com/w3c/imsc/IMSC1.1/imsc1/spec/ttml-ww-profiles.html#extent-version-2).

In a similar case (feature `#profile-version-2`), the attribute limitations not only stated in 7.12.13, but also in chapter 6. So for the sake of consistency I propose to state the attribute value restriction of `#extent-version-2` in chapter 6 as well.

**Comment by nigelmegitt** [comment]
Note that `#extent-version-2` has changed since this issue was raised.
