### ISSUE TITLE
No <length> in tts:extent due to prohibited #extent-measure

### ISSUE THREAD

**Issue by spoeschel** [w3c/imsc#382]
The `tts:extent` attribute currently cannot be set to a value containing `<length>`, as the [TTML2 feature `#extent-measure`](https://w3c.github.io/ttml2/#feature-extent-measure) is prohibited. This feature however is the only way to resolve `<extent>` to e.g. `<length> <length>`. I therefore opened w3c/ttml2#730.

**Comment by nigelmegitt** [comment]
My proposed solution at https://github.com/w3c/ttml2/issues/730#issuecomment-388376616 would partially solve this. However the disposition "prohibited" on `#extent-measure` would need to be adjusted since not all values are prohibited.

**Comment by palemieux** [comment]
`#extent-length` feature has been added to TTML2.
