### ISSUE TITLE
Missing #region-implied-animation

### ISSUE THREAD

**Issue by cconcolato** [w3c/imsc#387]
The feature #region-implied-animation is defined in https://w3c.github.io/ttml2/#feature-region-implied-animation but not listed in IMSC.

**Comment by nigelmegitt** [comment]
We should prohibit it, right?

**Comment by palemieux** [comment]
Fixed by https://github.com/w3c/imsc/commit/97ef61ae5d2d5d431bf657fdd88b0d2d7d253e7a , which omits `#region-implied-animation` and thus prohibits it.

**Comment by palemieux** [comment]
See also resolution at #366
