### ISSUE TITLE
Fix aspect ratio of itts:fillLineGap figures

### ISSUE THREAD

**Issue by spoeschel** [w3c/imsc#389]
When the two figures in [7.8.6 itts:fillLineGap](https://rawgit.com/w3c/imsc/IMSC1.1/imsc1/spec/ttml-ww-profiles.html#itts-fillLineGap) are rendered by common browsers (e.g. Firefox or Chrome), they appear horizontally squeezed and the original aspect ratio gets lost.

**Comment by nigelmegitt** [comment]
This doesn't happen at https://www.w3.org/TR/ttml-imsc1.0.1/#itts-fillLineGap but does happen at https://www.w3.org/TR/ttml-imsc1.1/#itts-fillLineGap - I haven't checked the difference, but that's a hint to find the fix.

**Comment by palemieux** [comment]
This is apparently a bug in `base.css`. See https://github.com/w3c/tr-design/issues/156.

**Comment by nigelmegitt** [comment]
@palemieux is it worth implementing the workaround at https://github.com/w3c/tr-design/issues/156#issuecomment-399218695 or would that cause other problems?
