### ISSUE TITLE
Refactor features per TTML2 CR2

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#390]
TTML2 CR2 has significantly refactored feature designators. IMSC 1.1 needs to be updated to match this refactoring.

**Comment by palemieux** [comment]
Ensure that all dependent features are listed and/or that a link to the TTML2 feature is provided.

See https://github.com/w3c/imsc/pull/388#issuecomment-397719302 and https://github.com/w3c/imsc/pull/388#issuecomment-397717017

**Comment by nigelmegitt** [comment]
@palemieux some features (e.g. `#extent-length-version-2`) were further refactored more recently than the last commit referencing this issue - now that the TTML2 ED is stable against features have you gone back round the loop one more time to check that the feature tables match?

**Comment by palemieux** [comment]
@nigelmegitt Yes, as part of https://github.com/w3c/imsc/pull/395
