### ISSUE TITLE
NOT FOUND

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#404]
Whereas `em` units are prohibited for use in `tts:origin` they are currently permitted in `tts:position` although `tts:origin` is not permitted if `tts:position` is used. I don't think that we agreed to permit the use of `em` units in `tts:position` so the constraint should be applied to `tts:position` also.

**Comment by palemieux** [comment]
See https://github.com/w3c/imsc/pull/397

**Comment by nigelmegitt** [comment]
Closing as a duplicate of #397.
