### ISSUE TITLE
Conformance conventions are in two places, differently

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#424]
§2 Document conventions and §4 Conformance both make statements about which parts of the document are normative, but those statements are different (though not contradictory). 

I suggest moving the first two paragraphs of §4 to §2 so that they are all in the same place, i.e. move the text:

>  As well as sections marked as non-normative, all authoring guidelines, diagrams, examples, and notes in this specification are non-normative. Everything else in this specification is normative.
>
> The key words MAY, SHALL, SHALL NOT, SHOULD, and SHOULD NOT are to be interpreted as described in [RFC2119].

**Comment by palemieux** [comment]
The prose in Section 4 is boilerplate auto-generated by respec. I plan to delete the duplicated text from Section 2 instead.
