### ISSUE TITLE
Document Instance conformance should mention §7.2

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#425]
In §4 Conformance the three bullets that define document conformance do not allow for foreign namespace content as per §7.2. We could either scope "Document Instance" in this case to be post-pruning according to TTML2 section 4 (currently only mentioned in an informative note in §7.2) or explicitly say "MAY contain elements or attributes neither explicitly permitted nor prohibited by the profile as per §7.2".

**Comment by palemieux** [comment]
TTML2 and Section 7.2 already admit foreign vocabulary.

**Comment by nigelmegitt** [comment]
Thanks, on re-reading it I agree, though it didn't look that way to me at first. Happy to close this with no change.
