### ISSUE TITLE
Image profile allows some style attributes but not initial element

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#429]
It seems inconsistent that the `initial` element is permitted in the Text Profile but prohibited from the Image Profile when there are style attributes that are permitted in Image Profile, such as `tts:backgroundColor`, `tts:display`, `tts:luminanceGain` etc. 

Raised in the requirements space at w3c/imsc-vnext-reqs#36.

**Comment by nigelmegitt** [comment]
Another data point here: §7.11 Style Resolution explicitly permits use of `initial` element for `itts:forcedDisplay` which is permitted in Image Profile, so this currently conflicts with the prohibition on `#initial` for Image Profile. So something needs to change here one way or another.

**Comment by palemieux** [comment]
>  Style Resolution explicitly permits use of initial element for itts:forcedDisplay which is permitted in Image Profile, so this currently conflicts with the prohibition on #initial for Image Profile. So something needs to change here one way or another.

The only thing that needs to change is the informative note: _The style properties above can be specified as attributes of the initial element specified at Section 10.1.1 of [ttml2-20180628]._ In fact, perhaps the note can be removed.
