### ISSUE TITLE
XML encoding is not a normative requirement

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#431]
Although UTF-8 encoding is a requirement in §7.1, I was surprised that I could not find a normative requirement to use an XML concrete encoding as recommended in TTML2 Appendix A anywhere. Please point to it if it is there, otherwise I propose adding a normative statement to §7.1 requiring that the document instance shall be concretely encoded as a well-formed XML 1.0 [XML 1.0] document in line with TTML2 appendix A.

**Comment by palemieux** [comment]
See also https://github.com/w3c/imsc/pull/438#discussion_r202639619 for a recommendation against the use of entity expansion
