### ISSUE TITLE
Strictly negative = negative.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#444]
The 'strictly' qualifier is superfluous.

**Comment by nigelmegitt** [comment]
There seems to be an interpretation that "negative" can include zero but "strictly negative" cannot, so I'm not sure if this issue is correct. I'm also not sure what the authoritative source for this is!

**Comment by skynavga** [comment]
The only possible context I can think of where "negative" can include zero is with certain floating point representations that assign a bit pattern to `-0` that is different than `+0`. However, if the former is encountered in a TTML document as a syntactic value, then I would expect it to be interned as `+0` (=0) in all cases, and only when a negative sign is syntactically permitted.  In the present context, `-0` is permitted in length expression syntax, but I would not expect `-0` to be a permitted value. So the text should simply say _negative_.

**Comment by palemieux** [comment]
>  but I would not expect -0 to be a permitted value.

`-0` computes to (is mathematically equivalent to) `0`, right? If so, why wouldn't it be permitted syntactically -- however weird it is? I am asking because there are a number of places where `< 0` is specified.

**Comment by skynavga** [comment]
ok, but this is at variance with language in TTML[12] which says in various places that some value(s) must not be negative, which excludes `-0` as well; it seems odd that IMSC should permit `-0` in some contexts when TTML does not; as this can be a source of confusion for authors and implementers, I suggest excluding `-0` as well and making it consistent with TTML language

**Comment by nigelmegitt** [comment]
I think `-0` is already excluded by "strictly negative". Do you mean that the use of "strictly" implies that where _not_ used then `0` and `-0` and `+0` are permitted in the context of negative numbers, and that this implication varies from the intended meaning of "negative" in TTML?

**Comment by palemieux** [comment]
@skynavga What does the term _non-negative_ mean in TTML2?

**Comment by skynavga** [comment]
in the context of lexical value syntax, negative means uses a `-` sign
in the context of lexical value syntax, non-negative means has no sign or uses a `+` sign
in the context of value semantics, non-negative x ≡ x≥0
in the context of value semantics, negative x ≡ x<0
`-0` is syntactically negative but semantically non-negative (=0=+0)
generally, when TTML says non-negative, then it means both syntactically and semantically non-negative, which means `-0` is not permitted as a lexical representation of `0`

**Comment by palemieux** [comment]
In XML schema, `nonNegativeInteger` (https://www.w3.org/TR/xmlschema-2/#nonNegativeInteger) allows `-0`.

**Comment by skynavga** [comment]
Thanks for pointing that out. TTML2 generally makes use of `<non-negative-number>` and `<non-negative-integer>`, which do not permit `-0`, but I see that `xsd:nonNegativeInteger` is also used in two places in the spec, which, for consistency, should be changed to `<non-negative-integer>`.

**Comment by palemieux** [comment]
Two other points of potential confusion:

- `<non-negative-integer>` does not include syntax with a `+` sign, e.g. `+1`
- _non-negative_ is used both in the context of specified value and computed values. In the case of the former, `-0` is arguably negative, but not in the case of the latter since `-0 == 0`

**Comment by palemieux** [comment]
In the context of IMSC 1.1 PR, I think the best we could do would be to clarify that _strictly negative_ means `< 0`, which seems to be the accepted definition. This would accept `-0` syntactically, which is equivalent to 0.

What is the downside of such an approach?

**Comment by nigelmegitt** [comment]
Surely `< 0` rejects `-0` even syntactically?

**Comment by palemieux** [comment]
AFAIK `-0 === 0` mathematically.

**Comment by palemieux** [comment]
@nigelmegitt I have clarified https://github.com/w3c/imsc/issues/444#issuecomment-418153862

**Comment by skynavga** [comment]
@nigelmegitt I am definitely opposed to your suggestion to prefer `xsd:nonNegativeInteger` over `<non-negative-integer>`; the use of the former was inadvertent, and only appears with `chunk@length`, `data@length`, and `isd:sequence@size` in TTML2; in contrast, the syntax and use of `<non-negative-integer>` goes back to TTML1 1ed and earlier, and was intentional;

IMO, we should not enable use of `-0=0`, and should remove the few (new TTML2) cases where it has slipped in.

**Comment by palemieux** [comment]
@skynavga Can you explain the rationale behind _IMO, we should not enable use of -0=0_?

**Comment by skynavga** [comment]
@palemieux sure, (1) the use of `xsd:nonNegativeInteger` in TTML2 was inadvertent: a mistake, when `<non-negative-integer>` was already available and used elsewhere; (2) there was never an intention (or discussion) of permitting the use of `-0`; (3) there is no conceivable technical or authorial use case for introducing `-0=0` in TTML2, when we have a pre-existing usage pattern that does not support it; (4) the introduction of `-0=0` creates an inconsistency, resulting in more implementation complexity and authorial semantics overloading (authors now have to keep track of where `-0` is permitted and where it is not permitted;

**Comment by palemieux** [comment]
@skynavga Ok, your argument seems limited to TTML2 and the use of `xsd:nonNegativeInteger`.

In the case of IMSC 1.1, _strictly negative_ applies to `tts:disparity`, which accepts `-0` per TTML2, so, in that case, IMSC 1.1 permits `-0` since the usual definition of _strictly negative_ is `<0`.

**Comment by skynavga** [comment]
@nigelmegitt actually, it (the prohibition on use of strictly negative) is said to apply to all BUT four style properties (including `tts:disparity`); however, your point is taken: `-0` is already sanctioned by `<length>`, so allowing it doesn't hurt anything in this context; nonetheless, I would still prefer to proscribe `-0` as well in these contexts in IMSC, since it doesn't have any additional utility, on the grounds that I had previously said that when TTML uses _non-negative_, it means both semantic and syntactically negative;

for example, TTML2 10.2.21 has

>The <length> value(s) used to express font size must be non-negative.

which I claim means both semantically and syntactically non-negative

**Comment by nigelmegitt** [comment]
> I claim means both semantically and syntactically non-negative

@skynavga is there anything in the spec that would lead readers to come to the same conclusion?

**Comment by nigelmegitt** [comment]
> there was never an intention (or discussion) of permitting the use of -0

@skynavga likewise there was never a discussion about whether to choose `xsd:nonNegativeInteger` or `<non-negative-integer>` but the changes that introduced those types with `xsd:nonNegativeInteger` were reviewed and approved, so we do have at least some process to point back at to say this was a WG choice.

I can see where `<non-negative-integer>` is used deliberately in the spec and it certainly makes sense in those places. However replacing `<xsd:nonNegativeInteger>` with `<non-negative-integer>` at this stage or in a 2nd Edition would create a compatibility issue as well as making validation slightly harder, so I would like to see a stronger motivation for doing so before accepting such a change.

**Comment by skynavga** [comment]
@nigelmegitt the evidence is indirect, in that `<non-negative-integer>` is defined without the ability to specify a sign, and, further, this was the case since DFXP days; there was no discussion of introducing `xsd:nonNegativeInteger`, which I now view as an error, since it introduces an inconsistency; when it was introduced in these few places,  I did not recall that it admitted `-0`, and most certainly would not have used it had I realized that to be the case; unfortunately, nobody pointed out the inconsistency at that time;

**Comment by palemieux** [comment]
> generally, when TTML says non-negative, then it means both syntactically and semantically
> non-negative, which means -0 is not permitted as a lexical representation of 0

I am no longer convinced this is the case having implemented validation for attributes such as `tts:backgroundExtent`. In the case of the latter, the specification states:

1. _both `<measure>` specifications must resolve (or be resolvable) to non-negative lengths_

2. that the value of the attribute is `<extent>`, which boils down to `<measure> <lwsp> <measure>`

Since `<measure>` is not limited to `<non-negative-integer>`, I would conclude that `-0` is permitted syntactically per (2), and permitted semantically per (1).
