### ISSUE TITLE
Deprecate #region-timing in Text Profile

### ISSUE THREAD

**Issue by cconcolato** [w3c/imsc#473]
It seems that there is no test for `#region-timing` see https://github.com/w3c/ttml2/issues/1073
I'm not aware of any use of this in the text profile. I would like to know if it could be deprecated from the Text profile.

**Comment by palemieux** [comment]
Test was added at https://github.com/w3c/imsc-tests/pull/86

Recommend closing as _Will Not Fix_

**Comment by nigelmegitt** [comment]
I also suspect deprecating could be a good move, but would accept closing with no change.
