### ISSUE TITLE
Feature designators in Section 6 point to TTML2 CR

### ISSUE THREAD

**Issue by cconcolato** [w3c/imsc#474]
The links from the feature designators in Section 6 point to TTML2 CR while they should point to the REC. Example, `#animation` uses https://www.w3.org/TR/2018/CR-ttml2-20180628/#feature-animation.

**Comment by nigelmegitt** [comment]
Thanks for raising this @cconcolato I'd noticed that in the past too but just in passing and forgot to raise it as an issue. Hopefully this is something we can update editorially in the Rec with minimal process.
