### ISSUE TITLE
Escaped % in schema causes some tools to error

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#476]
https://github.com/w3c/imsc/blob/6a0bdfe5c5baf709c894d336af36cf2a66dca3d6/imsc1/spec/xml-schemas/imsc1-parameters.xsd#L32

has the regex: `\+?(\d*\.\d+|\d+)\%`

The final `\` before the `%` is unnecessary since in XML regular expressions `%` does not need to be escaped, and indeed it causes some tools (Saxon) to generate an error validating the schema. Omitting the `\` seems to have no harmful effects, so I propose to delete it.

**Comment by palemieux** [comment]
Yes, it looks like `%` is not a [metacharacter](https://www.w3.org/TR/xmlschema11-2/#regexs) and does not need to be escaped.
