### ISSUE TITLE
Ambiguous `#position` constraints.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#486]
The following text at [1] is ambiguous:

>The tts:position attribute SHALL NOT be present in a Document Instance if any tts:origin attribute is also present.

In particular, it doesn't indicate the scope for evaluating the presence of `tts:origin`. Is it the entire document instance or the same `region` element on which `tts:position` is specified?

[1] https://www.w3.org/TR/ttml-imsc1.1/#text-position

**Comment by palemieux** [comment]
> Is it the entire document instance or the same `region` element on which `tts:position` is specified?

The entire document. I plan to prepare a PR to clarify.
