### ISSUE TITLE
Non-prohibition of partially supported features.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#488]
In §6 it is stated

>All features specified in [ttml2] are prohibited unless specified otherwise below

however, there appears to be no prohibition against the use of features that are marked as _partially supported_.

For example, `#base-version-2` includes support for `#base-general`, and §6 marks `#base-version-2` as "partially supported via #base", but does not otherwise state that the underlying features of `#base-version-2` that are not included in the underlying features of `#base` are prohibited.

The same comment applies to all other partially supported features.

If the intention is to prohibit underlying features not covered by statements of only partial support, then I would expect a general normative statement to be present that states something like:

>If a feature or extension is marked as partially supported, then the vocabulary, syntax, and attribute values of the feature or extension that are not included in the statement of partial support are prohibited.

This text should probably go into §4 _Conformance_.

**Comment by skynavga** [comment]
I should add that, as presently defined in IMSC 1.1, a validator may interpret, for example,

```
<body xml:base=".">...</body>
```

as permitted (non-prohibited) in which case reporting this usage as _invalid_ would be incorrect.

**Comment by skynavga** [comment]
Amending my above, I see that [TTML2] E.1.27 states:

>It is an error for a content profile to require or permit use of the #base-version-2 feature but prohibit use of any of the following features: #base or #base-general.

So perhaps it is not possible to prohibit a subset of a partially supported feature without running afoul of [TTML2] which pretty much repeats the above for every compound feature definition.

**Comment by cconcolato** [comment]
I agree the current text can be confusing. I also think the intent is to prohibit the features that are not explicitly supported. I would agree with your proposal in your initial statement.

**Comment by palemieux** [comment]
> So perhaps it is not possible to prohibit a subset of a partially supported feature without running afoul of [TTML2] which pretty much repeats the above for every compound feature definition.

@skynavga This is the reason why IMSC neither prohibit nor permits `#base-version-2`, but merely specifies the disposition of its subset features.

I suggest the note reads:

_A feature or extension marked as partially supported is neither prohibited nor permitted. Instead, the disposition of each of its subset extension or feature is specified individually._

**Comment by nigelmegitt** [comment]
I could live with either @skynavga 's original proposal or @palemieux 's modified one. 

One thing I don't like about @palemieux's suggestion in https://github.com/w3c/imsc/issues/488#issuecomment-540593048 is that I do not know what state "neither prohibited nor permitted" defines - it seems to be impossible. From that perspective @skynavga 's proposal is  clearer.

A simple tweak would be to change "neither prohibited nor permitted" to "neither completely prohibited nor completely permitted".

**Comment by palemieux** [comment]
> A simple tweak would be to change "neither prohibited nor permitted" to "neither completely prohibited nor completely permitted".

+1
