### ISSUE TITLE
#content disposition should be partial for image profile

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#494]
As defined, the `#content` feature includes support for `p`, `span`, and `br` elements, which are prohibited by the image profile at [1]. Therefore, support for what is permitted by the image profile is only partial.

[1] https://www.w3.org/TR/ttml-imsc1.1/#content

**Comment by palemieux** [comment]
_Partial support_ is used only when subset features/extensions are present, otherwise the pattern is merely add a note pointing to further constrain it in the body of the specification -- see `#fontFamily` for example.

I plan to do the same here.
