### ISSUE TITLE
Add informative note to tts:fontStyle recommending use of tts:shear instead of tts:fontStyle="italic" for Japanese text.

### ISSUE THREAD

**Issue by jmccrossan-fox** [w3c/imsc#495]
Per [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/font-style)
-  "italic" selects a particular version of the font, which might not exist. 
- when an "italic" version of the font does not exist, CSS silently converts "italic" to "oblique", which, by default, maps to a recommended shear of 14 deg.

Many Japanese fonts do not have an "italic" version. 

Consider adding an informative note in the definition of [tts:fontStyle](https://w3c.github.io/ttml2/index.html#style-attribute-fontStyle) highlighting the above and recommending that, to avoid indeterministic results, the content author specify [tts:shear](https://w3c.github.io/ttml2/index.html#style-attribute-shear) on Japanese text instead of tts:fontStyle="italic".

**Comment by nigelmegitt** [comment]
Since it is unclear looking at the thread, I'm noting that this issue arrived in this repository after being transferred from ttml2, with TTWG consensus.
