### ISSUE TITLE
font selection rules under-specified?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#516]
IMSC 1.2 introduces support for the `#font` feature from TTML2. This feature allows attributes such as font family name, unicode range, style, and weight to be specified, which can be used when selecting an actual font resource to use based on the computed style set that applies to a character or section of text within a span.

When we specified this we discussed the CSS3 `@font-face` rule and I _think_ the working assumption was that we were basing the font selection semantics on that specification. However TTML2 does not explicitly reference that rule anywhere, and certainly not in the section that defines font resources. Further, TTML2 does not define font selection semantics that are coincident with the `@font-face` semantics. The section on [tts:fontSelectionStrategy](https://www.w3.org/TR/ttml2/#style-attribute-fontSelectionStrategy) mentions only:

> When selecting among font resources that satisfy the font selection criteria, font resources that are referenced by a font element have priority over application or system supplied font resources.

without detailing any other algorithm for the defined term "[font selection process]".

I would in the first instance expect TTML2 to describe the semantics for font selection, by referencing `@font-face`. However, given that it does not do so, I think IMSC 1.2 must do so instead.

Reviewing IMSC 1.2 for this, I find:

* [css-fonts-3] is listed in the Normative References section but does not appear to be referenced from the document.
* There is no definition of the semantics for selecting a font given available font resources.

I think this needs to be addressed either in TTML2 or in IMSC 1.2. I'm open to either specification addressing this, but if we decide to address it in TTML2 then we should transfer this issue to the w3c/ttml2 repository.

**Comment by skynavga** [comment]
The pertinent language in TTML2 is found under §10.2.19

>Initial: | auto

and

>The presentation semantics of this property are those defined by [XSL-FO 1.1], §7.9.3

No use is ascribed to CSS `@font-face` semantics.

**Comment by skynavga** [comment]
It appears that the original proposal to use CSS `@font-face` came in the context of https://github.com/w3c/ttml2/issues/371, which was resolved by adopting `tts:fontSelectionStrategy` without making reference to `@font-face` functionality. I would suggest that if we want to bring in the newer (and richer) semantics of CSS3's Font Module, then it should be done by enhancing `tts:fontSelectionStrategy`, which would probably need to be done by introducing a new value for this attribute via a new module, e.g., `cssFontFace` or `fontFace` or just `css`.

**Comment by nigelmegitt** [comment]
Thanks for finding that @skynavga . It looks like we deferred referencing CSS font-face because there was no clear need for it. It is clear now that we do have a need for it due to IMSC 1.2, so I think we should look at specifying it _somewhere_ - as you said during today's call, it's a core thing, so the best place would be in TTML2.

**Comment by palemieux** [comment]
@nigelmegitt and @skynavga Per the recommendation at https://github.com/w3c/imsc/issues/516#issuecomment-572671116, what about moving this issue to the TTML repo?

**Comment by nigelmegitt** [comment]
@palemieux for me this is a question of timing and expediency. If, as I believe, this needs to be a normative part of IMSC 1.2 before we go to CR, then it is not clear to me that we can implement that in TTML2 in the necessary timescales. For that reason alone I am contemplating adding normative provision into IMSC 1.2 now and porting it to a future version of TTML2 later.

If we can get this into TTML2, perhaps in 2nd Edition, in time for IMSC 1.2, then I would be very much in favour of doing so, since I think that is a better outcome overall.

**Comment by skynavga** [comment]
This will require designing a new feature, specifically, specifying a new normative value for `tts:fontSelectionStrategy` along with a rich set of normative semantics (which may be had by referencing some portion of CSS3 Font Module, but will require a merger of semantics with the functionality present in the `font` element, which does not entirely match what is available via CSS3 Font Module). This will require testing and implementation work. This will require creating and specifying a new TTML Extension Module in which to define this new value. So just forget about doing this in IMSC1.2 or TTML2 3e.

**Comment by palemieux** [comment]
@nigelmegitt Stepping back for a second, what capabilities do you believe are missing from the current draft? Any sample document you can share?

**Comment by nigelmegitt** [comment]
@palemieux the capability missing is a defined mechanism for using the specified unicode range, style, weight etc to map to a specific external font resource. This is an interoperability issue because it means authors cannot rely on the font selection semantics in a reliable way. That in turn means that the usefulness of `#font` support is minimal.

In IMSC 1.2 there is no support for `#fontSelectionStrategy` which means that the `auto` value applies, which as per XSL-FO means that the behaviour is implementation defined. This is in line with TTML2 now.

@skynavga I agree that testing and implementation work would be needed, but I do not agree that a new extension module is needed. The initial proposal to define this implementation behaviour in IMSC 1.2 is achievable in my view, simply by including a normative statement that the font selection strategy shall be implemented in accordance with the semantics of `@font-face`, and explicitly mapping the TTML2 `font` element attributes to the CSS descriptors for font-face.

This proposal would not be in conflict with TTML2's existing semantics.

Tests would still be needed, but implementation complexity is not high, especially for CSS based implementations.

**Comment by palemieux** [comment]
> the specified unicode range, style, weight etc to map to a specific external font resource.

@nigelmegitt Isn't the selection strategy only triggered if there is overlap/ambiguity?

**Comment by nigelmegitt** [comment]
> Isn't the selection strategy only triggered if there is overlap/ambiguity?

@palemieux regardless of when it is triggered, it needs to be defined to be useful. However, I think it is risky to say "only" triggered if there is overlap/ambiguity: that may seem like a less important edge case to you, but I don't think we can put such a value judgement on it.

The intent of including `#font` included meeting the use case/requirement to be able to specify a font that uses fallback glyphs or even potentially private use area glyphs, where it could be that a particular external font resource is needed solely for a small subset of code points and a different font resource is needed for the remainder of the cases.

**Comment by palemieux** [comment]
> that may seem like a less important edge case to you, but I don't think we can put such a value judgement on it.

My question was not related to the relative importance of the use case.

If the ambiguity in `#fontSelectionStrategy` is triggered only when there is overlap, then the author should be able to avoid such overlap since the author has control over the provided fonts, right?

**Comment by palemieux** [comment]
> The initial proposal to define this implementation behaviour in IMSC 1.2 is achievable in my view, simply by including a normative statement that the font selection
> strategy shall be implemented in accordance with the semantics of @font-face, and explicitly mapping the TTML2 font element attributes to the CSS descriptors for font-face.

Perhaps IMSC 1.2 could both (a) recommend that implementations implement `@font-face` semantics and (b) authors avoid overlaps... with the objective of minimizing the potential for surprises.

**Comment by nigelmegitt** [comment]
I don't think it's reasonable to assume it is operationally desirable to avoid overlaps. For example consider that a content provider wants to specify both:

1. Their normal corporate font CorpFont
2. An extension to their normal corporate font ExtraCorpFont that specifies a fallback glyph for a 3rd party's logo when that company's name is used.

To do this they deliver CorpFont to their player as standard, and it does not need to be specified as an external resource in every IMSC document. This is efficient for normal distribution purposes.

A specific IMSC document needs to make mention of the 3rd party, and therefore includes a `font` pointing to ExtraCorpFont.

Now we have a code point overlap quite reasonably, and want to make sure that the player resolves it according to deterministic rules.

**Comment by skynavga** [comment]
TTML2 maps the `tts:fontSelectionStrategy` value `character` to the XSL-FO value `character-by-character`, about which XSL-FO says

>**Note:** This selection strategy is the same as the strategy used to select fonts in CSS.

I suppose you could stipulate in IMSC1.2 that the initial value of `tts:fontSelectionStrategy` SHOULD be treated as if `character` were specified and, moreover, that the procedure defined by [CSS Fonts] §5.2, _Matching Font Styles_, SHOULD be followed by implementations when multiple font resources are in scope for the purpose of assigning a font style to a character.

You also may want to consider adding a cautionary note that this language may change in the future if and when this language is migrated into a TTML core specification or module and the IMSC language replace with a reference to the migrated language.

**Comment by skynavga** [comment]
One more point, which is that this new language should be non-normative, or, at most, should be an implementation hint at this point. It is premature to bake this in as normative for a variety of reasons:

-  too late in the publishing cycle;
- it would necessitate additional testing/implementation activity;
- CSS Fonts is at present only an informative reference in TTML2;
- there are very likely semantic inconsistencies between CSS Fonts §5.2 and the rules specified under TTML2 §10.2.27 `tts:lineHeight` that determine _F0_, and, thence, _LH_;
- other unforeseen consequences

**Comment by nigelmegitt** [comment]
@skynavga I don't understand why the `character` strategy should be used. It looks as though that quoted text from XSL-FO is no longer completely accurate and has been overtaken by newer CSS specifications.

`auto` leaves it to be implementation dependent so it would be equally (or more) valid to assume `auto` and use current CSS semantics, if I've understood correctly.

On the point about the language being normative, it is not too late in the publishing cycle to make changes since IMSC 1.2 is at FPWD only. We certainly _could_ make a change if we wanted, though it could potentially incur some delay.

Your point about inconsistencies between CSS Fonts and `tts:lineHeight` certainly seems worth further consideration, however I think it should be possible to refer to CSS Fonts for the font selection rules without referring to it for line height computation.

I agree in principle that the font selection strategy used should modify the selection of _F0_ and therefore the line height calculation. However thinking about the practical side of this, and if it could make any difference, it seems to be one of two (edge) cases:

1. if the font family refers to font resources that have not been fetched, that font should not be in _FF_.
2. if the font family refers to font resources that have been fetched and there are multiple font resources for the same font family name, then line height calculation will only differ if the metrics in those font resources differ. That would be an interesting situation, and, I guess, an unexpected edge case. I would like to know if there are real world situations where people want to use font resources with different metrics like this.

**Comment by skynavga** [comment]
>I don't understand why the character strategy should be used.

Because XSL-FO says

>**Note:** This selection strategy is the same as the strategy used to select fonts in CSS.

And you are saying  you want the same behavior as CSS.

>It looks as though that quoted text from XSL-FO is no longer completely accurate and has been overtaken by newer CSS specifications.

Since we have adopted the XSL-FO semantics, then that is the semantics that we have adopted at present.

>`auto` leaves it to be implementation dependent so it would be equally (or more) valid to assume `auto` and use current CSS semantics, if I've understood correctly.

No. You can't declare that implementation dependent semantics means X  because then it is no longer implementation dependent.

Given the existence of subset fonts, where one may have multiple fonts where everything is the same (family names, sizes, styles, etc, except for glyphs and/or metrics, then you can't possibly predict it without going through the entire font matching, layout, and rendering process).

My opinion is that you are treating the possibility of making this late change far too lightly. This is a core semantic that can have potentially wide impact on processing and layout, and should not be entertained at this time, unless it is handled as a purely non-normative hint with more to follow at a later time as more thought, motivation, and implementation support is provided. I will probably register an objection to any attempt to fast tracking a normative change due lack of a firm motivating cause.

**Comment by nigelmegitt** [comment]
Thanks for that @skynavga .
