### ISSUE TITLE
APA WG comment: Add note on alt text

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/imsc#521]
With respect to the [7.12.2 altText](https://www.w3.org/TR/2019/WD-ttml-imsc1.2-20191128/#altText) named metadata item, this is directly related to the accessibility requirement of having an alternate text version for images ([Success Criterion 1.1.1 Non-text Content](https://www.w3.org/TR/2018/REC-WCAG21-20180605/#non-text-content)). Could you add a note here saying something like:

> Note:
> Authors are encouraged to provide text alternatives for every non-decorative image and/or compound image set by using the altText named metadata item. This is necessary for making the image in the document accessible to persons with (visual) disabilities, thus complying with
<https://www.w3.org/TR/2018/REC-WCAG21-20180605/#non-text-content> WCAG 2.1 success criterion 1.1.1 (Non-text content).

**Comment by palemieux** [comment]
@michael-n-cooper In [IMSC](https://www.w3.org/TR/ttml-imsc1.2/#general), `altText` is not used to offer a text alternative for image-based subtitles and captions. Instead a separate text-based subtitle or caption document is offered, and the term _necessary_ does not seem appropriate here. What about modifying the note at 5.1 along the lines of the following:

_The altText named metadata item also allows text equivalent string to be associated with an image. This allows, for example, indexation of the content, matching actual image contents to intended contents during quality checking of the document, and making the image in the document accessible to persons with (visual) disabilities during authoring._

**Comment by palemieux** [comment]
See also https://github.com/w3c/imsc/issues/321

**Comment by gzimmermann** [comment]
What about the following note, based on the proposal by @palemieux :
"The altText named metadata item also allows a text equivalent string to be associated with an image. This allows, for example, indexation of the content, matching actual image contents to intended contents during quality checking of the document, and making the image in the document accessible to timed text _authors_ with (visual) disabilities. Note that, for offering a text-based alternative experience to the _consumer_, a separate text-based subtitle or caption document is necessary."

**Comment by palemieux** [comment]
@gzimmermann See #542. The last sentence of the note at https://github.com/w3c/imsc/issues/521#issuecomment-617609425 is integrated in the paragraph above the note.

**Comment by gzimmermann** [comment]
Okay with me.

**Comment by michael-n-cooper** [comment]
APA agrees with disposition.

**Comment by michael-n-cooper** [comment]
Re-adding a11y-needs-resolution label because of new information about how the horizontal review tracker works, but this is still signed off from APA.
