### ISSUE TITLE
Glyph vs code point in HRM

### ISSUE THREAD

**Issue by plehegar** [w3c/imsc#69]
The statement "Gr and Gc shall include only glyphs in presented regions and shall not include a [UNICODE] Code Point if it does not result in a change to presentation, e.g. the Code Point is ignored." is rather unusual in that it erroneously refers to glyphs in terms of a Unicode Code Point. Glyphs and glyphs codes are not directly related to Unicode code points. It would be better to say that a glyph that does not contain any renderable outline is ignored. But that is rather redundant since font designers do not include glyphs in fonts that do not have a renderable outline.

(raised by Glenn Adams on 2015-09-21)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/429

**Comment by palemieux** [comment]
Addressed at c7eefbe6831c185fa92ae395b31181a601634152

See #68

**Comment by palemieux** [comment]
Closed per #68
