### ISSUE TITLE
Allows use of cell unit on ebutts:linePadding but does not require ttp:cellResolution

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#81]
If cell units are used with ebutts:linePadding, then the author probably should explicitly specify cell resolution, along the same lines how use of pixel unit requires tts:extent on root.

**Comment by palemieux** [comment]
TTML1 specifies a default value for cellResolution, so cellResolution does not need to be specified on \<tt\>. Furthermore, this would be a divergence from CFF-TT, which forbids cellResolution on \<tt\>.

**Comment by skynavga** [comment]
ok, but TTML1 specifies a default frame rate, so by that logic one shouldn't need to specify it if using a frame metric

**Comment by skynavga** [comment]
also regarding the CFF-TT prohibition, that prohibition doesn't hold in IMSC1, so that doesn't seem relevant

**Comment by skynavga** [comment]
section 6.10

#cellResolution	permitted

**Comment by palemieux** [comment]
Right! cellResolution is permitted on <tt> per http://www.w3.org/AudioVideo/TT/tracker/issues/332 .

Since cellResolution has a default value ("32 15"), its presence on <tt> is nevertheless not required.

Are you merely suggesting that authors should be encouraged to set its value explicitly?
