### ISSUE TITLE
Possibly ambiguous constraint on timing verification

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#83]
Section 6.10 under #timing says:

"For any content element that contains br elements or text nodes or a smpte:backgroundImage attribute, the begin and end attributes should be specified on the content element or at least one of its ancestors."

As written, this constraint (that begin/end be specified) does not apply to a \<p/\> or a \<span/\> that is empty. Is that intended?

**Comment by palemieux** [comment]
I believe it was the intent at https://lists.w3.org/Archives/Public/public-tt/2015May/0001.html
