### ISSUE TITLE
"Related Video Object frame" is an undefined term

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#84]
The term "Related Video Object frame" is used in §6.7.1 ittp:aspectRatio, however it is unclear what it means. 

Can I suggest that we define it to mean the area in which the video is displayed? 

This is to allow for cases where there is overscan or a different aspect ratio video display area to encoded video, for example, in which case I think the assumption is that an area as big as can be displayed is allocated to the root container extent, with the shape being defined by `ittp:aspectRatio`.

**Comment by palemieux** [comment]
_Related Video Object_ is defined as _sequence of image frames, each a rectangular array of pixels_, so yes I would consider _Related Video Object frame_ to mean the area onto which the sequence of image frames is displayed.

**Comment by nigelmegitt** [comment]
Yes, I think that probably works. I'm actually just iterating through all of the variables of `ittp:aspectRatio`, video aspect ratio and display aspect ratio right now, so will confirm my view. The important thing here is that, thinking about the difference between the encoded/decoded video frame and the display on which it is presented, we take a view on whether:

1. We leave it ambiguous and therefore implementation-dependent or context-dependent in which area the root container is centred and maximised.
2. We specify that it is the decoded video frame.
3. We specify that it is the viewport of the video display.

**Comment by nigelmegitt** [comment]
Have completed my analysis and realised that it's (as ever) more complicated than just a single option. It depends greatly on what the video object is doing to the video, in the case that the video does not have the same aspect ratio as the viewport in which it is being down (or the glass in the case of full screen).

See [IMSC aspectRatio analysis.pdf](https://github.com/w3c/imsc/files/37721/IMSC.aspectRatio.analysis.pdf) for details. 

My conclusion is that if there is a single _least bad_ option then it is to scale the root container region to the display, but a better but _more complex_ option is to scale it to the video if the video is being scaled to fit the display, or to the display otherwise.

**Comment by palemieux** [comment]
Thanks for the analysis! Doesn't this mirror to the challenges that the industry faces with video? The approach with the latter depends on the target application, e.g. sometimes two versions of the video are provided, sometimes a center-cut-enabled version is provided, etc. In some cases, the choice to not display the video in its entirety is driven by the user, e.g. "fill" button, and the user can change his/her mind if the result is not pleasant, e.g. center cut of very widescreen content.

Just as with video, I think the safest approach is to capture authorial intent, i.e. position of the caption/subtitles relative to elements in the image frame, as closely as possible based on what is available at time of authoring, i.e. the related video object.

I have proposed a note -- see #89.

This is similar in my mind to the approach taken in Section 6.6.
