### ISSUE TITLE
Old process reference

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#92]
ReSpec warns that the 2014 process has been superseded by the 2015 process. Since we adopted the 2015 process we should fix IMSC up to reference it.

**Comment by palemieux** [comment]
Ok. I do not recall the 2015 process being adopted. Can you provide a link to the minutes?

**Comment by palemieux** [comment]
See https://www.w3.org/AudioVideo/TT/tracker/actions/451

**Comment by palemieux** [comment]
Propose to adopt 2015 Process based on https://www.w3.org/wiki/ProcessTransition2015 and small differences between 2014 and 2015 Process.
