### ISSUE TITLE
#transformation is listed as permitted but #profile is constrained

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#93]
Since the `ttp:profile` element is prohibited, support for the `#profile` feature is in fact constrained. The `#transformation` feature depends on `#profile` but the constraint is not present. It would be worth adding a Provision to `#transformation` to clarify that the constraints defined against `#profile` apply.

**Comment by palemieux** [comment]
Addressed as part of #85 (See PR #87)

**Comment by nigelmegitt** [comment]
Ah, sorry, I forgot we hadn't merged that yet.

**Comment by nigelmegitt** [comment]
Closing as a duplicate of #85.
