### ISSUE TITLE
Image profile documents generate no ISDs

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#94]
According to TTML1's [construct intermediate document] process in §9.3.2 _empty_ content elements are pruned. Since image profile documents are not permitted to contain `p`, `span` or `br` elements and entities in other namespaces are ignored, the `div` elements are all empty according to TTML1 and will be pruned, resulting in there being no ISDs generated at all. I think some wording in IMSC may be needed to indicate that for the purpose of ISD generation a `div` element with a resolvable `smpte:backgroundImage` attribute shall not be considered empty.

**Comment by palemieux** [comment]
Addresses as suggested.
