### ISSUE TITLE
Need to tie image size to the relevant presented region not just any presented region.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#96]
§8.2.1 defines a presented image:

> A presented image is a `div` element with a `smpte:backgroundImage` attribute that does not extend beyond a presented region.

where _presented region_ is defined in §6.8.1.

There are at least two issues with the sentence in §8.2.1, that means it does not match the correct text in §8.3:
1. it is not clear that the size of the image is constrained by the specific region in which the div is flowed; rather it can be any presented region - and up to 4 can be simultaneously visible, each having a different size.
2. the _attribute_ does not have a size in any meaningful way; rather the referenced image has a size.

Suggested fix:

> A presented image is a `div` element with a `smpte:backgroundImage` attribute that references an image whose extent is no larger than the extent of the presented region into which the `div` is flowed.

**Comment by nigelmegitt** [comment]
Fine as is, but I think superseded by the pull request for #97 that incorporates this and may also be modified to be clearer about the image size equality requirement. Am now wishing we could merge the two issues somehow...

**Comment by palemieux** [comment]
I made the change in pull request #98, and merged it into #99.
