### ISSUE TITLE
backgroundImage specification needs to require the image to be displayed

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#97]
§8.3 describes the syntax of a `div` element that has a `smpte:backgroundImage` attribute but does not require that the image is processed as defined in SMPTE-TT.

At least a comment like that on TTML2's `tts:backgroundImage` attribute would be useful:

> **Note:**
>
> The semantics of the style property represented by this attribute are based upon that defined by [XSL 1.1], § 7.8.3.

This matches what's in SMPTE-TT by the way.

I think a cleaner thing to do would be to add a new section before §8.3 (making the current §8.3 §8.4 etc) to describe `smpte:backgroundImage`as being a mechanism for displaying an image in a region with the duration specified by element element on which it is specified, as defined by [SMPTE-TT] and including the note above. 

This section should normatively define that the referenced image must have numerically equal size (in its pixels) as the extent of the region (in TTML pixels) regardless of pixel aspect ratio, and that conformant presentation processors shall scale and display that image coincident with the TTML region into which the content element is flowed.

Then the section defining constraints on `div` becomes simpler and only relates to constraints on `div`.

**Comment by palemieux** [comment]
Doesn't stating that "#image" is "permitted" (Section 8.4) require processing of smpte:backgroundImage per SMPTE ST 2052-1?

**Comment by nigelmegitt** [comment]
Yes, I think it might. I had second thoughts about this issue after I raised it. As long as there's a clear spec path from smpte:backgroundImage to ST-2052 (SMPTE-TT spec) and then onto XSL-FO then it's okay. It's just a bit sparse looking as is, but maybe less is indeed more...

**Comment by nigelmegitt** [comment]
Having looked at in even more detail, ST-2052 has a bug in it that could be read as breaking the formal conformance requirements traceability. If you follow through, IMSC 1 pemits `smpte:#image` extension. ST2052 defines that as transforming an enumerated set of vocabulary as "defined in Section 5.7.3." however the key piece of vocabulary that we're interested in has no definition in that section. Instead what the document presumably means is the vocabulary regardless of where it is defined - in this case `smpte:backgroundImage` is defined in Section 5.5.2, including the crucial line:

> The semantics of the style property represented by this attribute shall follow those defined in W3C XSL 1.1, Section 7.8.3.

So this issue has migrated from what I initially thought as being the problem to being something much less impactful and more prosaic, but that still needs addressing. I suggest making a change to IMSC 1 §8.4 on the `#image` row of the table, along the lines of:

> `smpte:backgroundImage` MAY be used.

becomes

> `smpte:backgroundImage` MAY be used and the semantics of the attribute SHALL be defined by Section 5.5.2 of [ST2052-1].

**Comment by nigelmegitt** [comment]
One further change needed I think, to state that the size equality we're defining is numerical equality between the PNG pixel size of the image and the TTML pixel size (value of `tts:extent`) of the region, assuming that is what we mean. Otherwise we should state that the image shall be scaled to the same rendered size as the region, and the equality requirement is meaningless.
